// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetReverseProxyDomainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetReverseProxyDomainArgs Empty = new GetReverseProxyDomainArgs();

    @Import(name="domain")
    private @Nullable Output<String> domain;

    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    @Import(name="validated")
    private @Nullable Output<Boolean> validated;

    public Optional<Output<Boolean>> validated() {
        return Optional.ofNullable(this.validated);
    }

    private GetReverseProxyDomainArgs() {}

    private GetReverseProxyDomainArgs(GetReverseProxyDomainArgs $) {
        this.domain = $.domain;
        this.id = $.id;
        this.type = $.type;
        this.validated = $.validated;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetReverseProxyDomainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetReverseProxyDomainArgs $;

        public Builder() {
            $ = new GetReverseProxyDomainArgs();
        }

        public Builder(GetReverseProxyDomainArgs defaults) {
            $ = new GetReverseProxyDomainArgs(Objects.requireNonNull(defaults));
        }

        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public Builder validated(@Nullable Output<Boolean> validated) {
            $.validated = validated;
            return this;
        }

        public Builder validated(Boolean validated) {
            return validated(Output.of(validated));
        }

        public GetReverseProxyDomainArgs build() {
            return $;
        }
    }

}
