// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetScimPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetScimPlainArgs Empty = new GetScimPlainArgs();

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="providerName")
    private @Nullable String providerName;

    public Optional<String> providerName() {
        return Optional.ofNullable(this.providerName);
    }

    private GetScimPlainArgs() {}

    private GetScimPlainArgs(GetScimPlainArgs $) {
        this.id = $.id;
        this.providerName = $.providerName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetScimPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetScimPlainArgs $;

        public Builder() {
            $ = new GetScimPlainArgs();
        }

        public Builder(GetScimPlainArgs defaults) {
            $ = new GetScimPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public Builder providerName(@Nullable String providerName) {
            $.providerName = providerName;
            return this;
        }

        public GetScimPlainArgs build() {
            return $;
        }
    }

}
