// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.github.kitstream.netbird.inputs.PolicyRuleArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PolicyState extends com.pulumi.resources.ResourceArgs {

    public static final PolicyState Empty = new PolicyState();

    /**
     * Policy Description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Policy Description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Policy enabled
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Policy enabled
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Policy Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Policy Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="rule")
    private @Nullable Output<PolicyRuleArgs> rule;

    public Optional<Output<PolicyRuleArgs>> rule() {
        return Optional.ofNullable(this.rule);
    }

    /**
     * Posture checks associated with policy
     * 
     */
    @Import(name="sourcePostureChecks")
    private @Nullable Output<List<String>> sourcePostureChecks;

    /**
     * @return Posture checks associated with policy
     * 
     */
    public Optional<Output<List<String>>> sourcePostureChecks() {
        return Optional.ofNullable(this.sourcePostureChecks);
    }

    private PolicyState() {}

    private PolicyState(PolicyState $) {
        this.description = $.description;
        this.enabled = $.enabled;
        this.name = $.name;
        this.rule = $.rule;
        this.sourcePostureChecks = $.sourcePostureChecks;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PolicyState $;

        public Builder() {
            $ = new PolicyState();
        }

        public Builder(PolicyState defaults) {
            $ = new PolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Policy Description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Policy Description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enabled Policy enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Policy enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param name Policy Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Policy Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder rule(@Nullable Output<PolicyRuleArgs> rule) {
            $.rule = rule;
            return this;
        }

        public Builder rule(PolicyRuleArgs rule) {
            return rule(Output.of(rule));
        }

        /**
         * @param sourcePostureChecks Posture checks associated with policy
         * 
         * @return builder
         * 
         */
        public Builder sourcePostureChecks(@Nullable Output<List<String>> sourcePostureChecks) {
            $.sourcePostureChecks = sourcePostureChecks;
            return this;
        }

        /**
         * @param sourcePostureChecks Posture checks associated with policy
         * 
         * @return builder
         * 
         */
        public Builder sourcePostureChecks(List<String> sourcePostureChecks) {
            return sourcePostureChecks(Output.of(sourcePostureChecks));
        }

        /**
         * @param sourcePostureChecks Posture checks associated with policy
         * 
         * @return builder
         * 
         */
        public Builder sourcePostureChecks(String... sourcePostureChecks) {
            return sourcePostureChecks(List.of(sourcePostureChecks));
        }

        public PolicyState build() {
            return $;
        }
    }

}
