// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNetworkRouterResult {
    private Boolean enabled;
    private String id;
    private Boolean masquerade;
    private Integer metric;
    private String networkId;
    private String peer;
    private List<String> peerGroups;

    private GetNetworkRouterResult() {}
    public Boolean enabled() {
        return this.enabled;
    }
    public String id() {
        return this.id;
    }
    public Boolean masquerade() {
        return this.masquerade;
    }
    public Integer metric() {
        return this.metric;
    }
    public String networkId() {
        return this.networkId;
    }
    public String peer() {
        return this.peer;
    }
    public List<String> peerGroups() {
        return this.peerGroups;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkRouterResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabled;
        private String id;
        private Boolean masquerade;
        private Integer metric;
        private String networkId;
        private String peer;
        private List<String> peerGroups;
        public Builder() {}
        public Builder(GetNetworkRouterResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.id = defaults.id;
    	      this.masquerade = defaults.masquerade;
    	      this.metric = defaults.metric;
    	      this.networkId = defaults.networkId;
    	      this.peer = defaults.peer;
    	      this.peerGroups = defaults.peerGroups;
        }

        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder masquerade(Boolean masquerade) {
            if (masquerade == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "masquerade");
            }
            this.masquerade = masquerade;
            return this;
        }
        @CustomType.Setter
        public Builder metric(Integer metric) {
            if (metric == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "metric");
            }
            this.metric = metric;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(String networkId) {
            if (networkId == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "networkId");
            }
            this.networkId = networkId;
            return this;
        }
        @CustomType.Setter
        public Builder peer(String peer) {
            if (peer == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "peer");
            }
            this.peer = peer;
            return this;
        }
        @CustomType.Setter
        public Builder peerGroups(List<String> peerGroups) {
            if (peerGroups == null) {
              throw new MissingRequiredPropertyException("GetNetworkRouterResult", "peerGroups");
            }
            this.peerGroups = peerGroups;
            return this;
        }
        public Builder peerGroups(String... peerGroups) {
            return peerGroups(List.of(peerGroups));
        }
        public GetNetworkRouterResult build() {
            final var _resultValue = new GetNetworkRouterResult();
            _resultValue.enabled = enabled;
            _resultValue.id = id;
            _resultValue.masquerade = masquerade;
            _resultValue.metric = metric;
            _resultValue.networkId = networkId;
            _resultValue.peer = peer;
            _resultValue.peerGroups = peerGroups;
            return _resultValue;
        }
    }
}
