// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPostureCheckOsVersionCheck {
    private String androidMinVersion;
    private String darwinMinVersion;
    private String iosMinVersion;
    private String linuxMinKernelVersion;
    private String windowsMinKernelVersion;

    private GetPostureCheckOsVersionCheck() {}
    public String androidMinVersion() {
        return this.androidMinVersion;
    }
    public String darwinMinVersion() {
        return this.darwinMinVersion;
    }
    public String iosMinVersion() {
        return this.iosMinVersion;
    }
    public String linuxMinKernelVersion() {
        return this.linuxMinKernelVersion;
    }
    public String windowsMinKernelVersion() {
        return this.windowsMinKernelVersion;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPostureCheckOsVersionCheck defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String androidMinVersion;
        private String darwinMinVersion;
        private String iosMinVersion;
        private String linuxMinKernelVersion;
        private String windowsMinKernelVersion;
        public Builder() {}
        public Builder(GetPostureCheckOsVersionCheck defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.androidMinVersion = defaults.androidMinVersion;
    	      this.darwinMinVersion = defaults.darwinMinVersion;
    	      this.iosMinVersion = defaults.iosMinVersion;
    	      this.linuxMinKernelVersion = defaults.linuxMinKernelVersion;
    	      this.windowsMinKernelVersion = defaults.windowsMinKernelVersion;
        }

        @CustomType.Setter
        public Builder androidMinVersion(String androidMinVersion) {
            if (androidMinVersion == null) {
              throw new MissingRequiredPropertyException("GetPostureCheckOsVersionCheck", "androidMinVersion");
            }
            this.androidMinVersion = androidMinVersion;
            return this;
        }
        @CustomType.Setter
        public Builder darwinMinVersion(String darwinMinVersion) {
            if (darwinMinVersion == null) {
              throw new MissingRequiredPropertyException("GetPostureCheckOsVersionCheck", "darwinMinVersion");
            }
            this.darwinMinVersion = darwinMinVersion;
            return this;
        }
        @CustomType.Setter
        public Builder iosMinVersion(String iosMinVersion) {
            if (iosMinVersion == null) {
              throw new MissingRequiredPropertyException("GetPostureCheckOsVersionCheck", "iosMinVersion");
            }
            this.iosMinVersion = iosMinVersion;
            return this;
        }
        @CustomType.Setter
        public Builder linuxMinKernelVersion(String linuxMinKernelVersion) {
            if (linuxMinKernelVersion == null) {
              throw new MissingRequiredPropertyException("GetPostureCheckOsVersionCheck", "linuxMinKernelVersion");
            }
            this.linuxMinKernelVersion = linuxMinKernelVersion;
            return this;
        }
        @CustomType.Setter
        public Builder windowsMinKernelVersion(String windowsMinKernelVersion) {
            if (windowsMinKernelVersion == null) {
              throw new MissingRequiredPropertyException("GetPostureCheckOsVersionCheck", "windowsMinKernelVersion");
            }
            this.windowsMinKernelVersion = windowsMinKernelVersion;
            return this;
        }
        public GetPostureCheckOsVersionCheck build() {
            final var _resultValue = new GetPostureCheckOsVersionCheck();
            _resultValue.androidMinVersion = androidMinVersion;
            _resultValue.darwinMinVersion = darwinMinVersion;
            _resultValue.iosMinVersion = iosMinVersion;
            _resultValue.linuxMinKernelVersion = linuxMinKernelVersion;
            _resultValue.windowsMinKernelVersion = windowsMinKernelVersion;
            return _resultValue;
        }
    }
}
