// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.netbird.netbird.outputs.GetPolicyRule;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetPolicyResult {
    private String description;
    private Boolean enabled;
    private String id;
    private String name;
    private @Nullable List<GetPolicyRule> rules;
    private List<String> sourcePostureChecks;

    private GetPolicyResult() {}
    public String description() {
        return this.description;
    }
    public Boolean enabled() {
        return this.enabled;
    }
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public List<GetPolicyRule> rules() {
        return this.rules == null ? List.of() : this.rules;
    }
    public List<String> sourcePostureChecks() {
        return this.sourcePostureChecks;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPolicyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private Boolean enabled;
        private String id;
        private String name;
        private @Nullable List<GetPolicyRule> rules;
        private List<String> sourcePostureChecks;
        public Builder() {}
        public Builder(GetPolicyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.enabled = defaults.enabled;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.rules = defaults.rules;
    	      this.sourcePostureChecks = defaults.sourcePostureChecks;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder rules(@Nullable List<GetPolicyRule> rules) {

            this.rules = rules;
            return this;
        }
        public Builder rules(GetPolicyRule... rules) {
            return rules(List.of(rules));
        }
        @CustomType.Setter
        public Builder sourcePostureChecks(List<String> sourcePostureChecks) {
            if (sourcePostureChecks == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "sourcePostureChecks");
            }
            this.sourcePostureChecks = sourcePostureChecks;
            return this;
        }
        public Builder sourcePostureChecks(String... sourcePostureChecks) {
            return sourcePostureChecks(List.of(sourcePostureChecks));
        }
        public GetPolicyResult build() {
            final var _resultValue = new GetPolicyResult();
            _resultValue.description = description;
            _resultValue.enabled = enabled;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.rules = rules;
            _resultValue.sourcePostureChecks = sourcePostureChecks;
            return _resultValue;
        }
    }
}
