// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetRouteResult {
    private List<String> accessControlGroups;
    private String description;
    private List<String> domains;
    private Boolean enabled;
    private List<String> groups;
    private String id;
    private Boolean keepRoute;
    private Boolean masquerade;
    private Integer metric;
    private String network;
    private String networkId;
    private String networkType;
    private String peer;
    private List<String> peerGroups;

    private GetRouteResult() {}
    public List<String> accessControlGroups() {
        return this.accessControlGroups;
    }
    public String description() {
        return this.description;
    }
    public List<String> domains() {
        return this.domains;
    }
    public Boolean enabled() {
        return this.enabled;
    }
    public List<String> groups() {
        return this.groups;
    }
    public String id() {
        return this.id;
    }
    public Boolean keepRoute() {
        return this.keepRoute;
    }
    public Boolean masquerade() {
        return this.masquerade;
    }
    public Integer metric() {
        return this.metric;
    }
    public String network() {
        return this.network;
    }
    public String networkId() {
        return this.networkId;
    }
    public String networkType() {
        return this.networkType;
    }
    public String peer() {
        return this.peer;
    }
    public List<String> peerGroups() {
        return this.peerGroups;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRouteResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> accessControlGroups;
        private String description;
        private List<String> domains;
        private Boolean enabled;
        private List<String> groups;
        private String id;
        private Boolean keepRoute;
        private Boolean masquerade;
        private Integer metric;
        private String network;
        private String networkId;
        private String networkType;
        private String peer;
        private List<String> peerGroups;
        public Builder() {}
        public Builder(GetRouteResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessControlGroups = defaults.accessControlGroups;
    	      this.description = defaults.description;
    	      this.domains = defaults.domains;
    	      this.enabled = defaults.enabled;
    	      this.groups = defaults.groups;
    	      this.id = defaults.id;
    	      this.keepRoute = defaults.keepRoute;
    	      this.masquerade = defaults.masquerade;
    	      this.metric = defaults.metric;
    	      this.network = defaults.network;
    	      this.networkId = defaults.networkId;
    	      this.networkType = defaults.networkType;
    	      this.peer = defaults.peer;
    	      this.peerGroups = defaults.peerGroups;
        }

        @CustomType.Setter
        public Builder accessControlGroups(List<String> accessControlGroups) {
            if (accessControlGroups == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "accessControlGroups");
            }
            this.accessControlGroups = accessControlGroups;
            return this;
        }
        public Builder accessControlGroups(String... accessControlGroups) {
            return accessControlGroups(List.of(accessControlGroups));
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder domains(List<String> domains) {
            if (domains == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "domains");
            }
            this.domains = domains;
            return this;
        }
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder groups(List<String> groups) {
            if (groups == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "groups");
            }
            this.groups = groups;
            return this;
        }
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder keepRoute(Boolean keepRoute) {
            if (keepRoute == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "keepRoute");
            }
            this.keepRoute = keepRoute;
            return this;
        }
        @CustomType.Setter
        public Builder masquerade(Boolean masquerade) {
            if (masquerade == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "masquerade");
            }
            this.masquerade = masquerade;
            return this;
        }
        @CustomType.Setter
        public Builder metric(Integer metric) {
            if (metric == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "metric");
            }
            this.metric = metric;
            return this;
        }
        @CustomType.Setter
        public Builder network(String network) {
            if (network == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "network");
            }
            this.network = network;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(String networkId) {
            if (networkId == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "networkId");
            }
            this.networkId = networkId;
            return this;
        }
        @CustomType.Setter
        public Builder networkType(String networkType) {
            if (networkType == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "networkType");
            }
            this.networkType = networkType;
            return this;
        }
        @CustomType.Setter
        public Builder peer(String peer) {
            if (peer == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "peer");
            }
            this.peer = peer;
            return this;
        }
        @CustomType.Setter
        public Builder peerGroups(List<String> peerGroups) {
            if (peerGroups == null) {
              throw new MissingRequiredPropertyException("GetRouteResult", "peerGroups");
            }
            this.peerGroups = peerGroups;
            return this;
        }
        public Builder peerGroups(String... peerGroups) {
            return peerGroups(List.of(peerGroups));
        }
        public GetRouteResult build() {
            final var _resultValue = new GetRouteResult();
            _resultValue.accessControlGroups = accessControlGroups;
            _resultValue.description = description;
            _resultValue.domains = domains;
            _resultValue.enabled = enabled;
            _resultValue.groups = groups;
            _resultValue.id = id;
            _resultValue.keepRoute = keepRoute;
            _resultValue.masquerade = masquerade;
            _resultValue.metric = metric;
            _resultValue.network = network;
            _resultValue.networkId = networkId;
            _resultValue.networkType = networkType;
            _resultValue.peer = peer;
            _resultValue.peerGroups = peerGroups;
            return _resultValue;
        }
    }
}
