// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetSetupKeyResult {
    private Boolean allowExtraDnsLabels;
    private List<String> autoGroups;
    private Boolean ephemeral;
    private String expires;
    private String id;
    private String lastUsed;
    private String name;
    private Boolean revoked;
    private String state;
    private String type;
    private String updatedAt;
    private Integer usageLimit;
    private Integer usedTimes;
    private Boolean valid;

    private GetSetupKeyResult() {}
    public Boolean allowExtraDnsLabels() {
        return this.allowExtraDnsLabels;
    }
    public List<String> autoGroups() {
        return this.autoGroups;
    }
    public Boolean ephemeral() {
        return this.ephemeral;
    }
    public String expires() {
        return this.expires;
    }
    public String id() {
        return this.id;
    }
    public String lastUsed() {
        return this.lastUsed;
    }
    public String name() {
        return this.name;
    }
    public Boolean revoked() {
        return this.revoked;
    }
    public String state() {
        return this.state;
    }
    public String type() {
        return this.type;
    }
    public String updatedAt() {
        return this.updatedAt;
    }
    public Integer usageLimit() {
        return this.usageLimit;
    }
    public Integer usedTimes() {
        return this.usedTimes;
    }
    public Boolean valid() {
        return this.valid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSetupKeyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean allowExtraDnsLabels;
        private List<String> autoGroups;
        private Boolean ephemeral;
        private String expires;
        private String id;
        private String lastUsed;
        private String name;
        private Boolean revoked;
        private String state;
        private String type;
        private String updatedAt;
        private Integer usageLimit;
        private Integer usedTimes;
        private Boolean valid;
        public Builder() {}
        public Builder(GetSetupKeyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowExtraDnsLabels = defaults.allowExtraDnsLabels;
    	      this.autoGroups = defaults.autoGroups;
    	      this.ephemeral = defaults.ephemeral;
    	      this.expires = defaults.expires;
    	      this.id = defaults.id;
    	      this.lastUsed = defaults.lastUsed;
    	      this.name = defaults.name;
    	      this.revoked = defaults.revoked;
    	      this.state = defaults.state;
    	      this.type = defaults.type;
    	      this.updatedAt = defaults.updatedAt;
    	      this.usageLimit = defaults.usageLimit;
    	      this.usedTimes = defaults.usedTimes;
    	      this.valid = defaults.valid;
        }

        @CustomType.Setter
        public Builder allowExtraDnsLabels(Boolean allowExtraDnsLabels) {
            if (allowExtraDnsLabels == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "allowExtraDnsLabels");
            }
            this.allowExtraDnsLabels = allowExtraDnsLabels;
            return this;
        }
        @CustomType.Setter
        public Builder autoGroups(List<String> autoGroups) {
            if (autoGroups == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "autoGroups");
            }
            this.autoGroups = autoGroups;
            return this;
        }
        public Builder autoGroups(String... autoGroups) {
            return autoGroups(List.of(autoGroups));
        }
        @CustomType.Setter
        public Builder ephemeral(Boolean ephemeral) {
            if (ephemeral == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "ephemeral");
            }
            this.ephemeral = ephemeral;
            return this;
        }
        @CustomType.Setter
        public Builder expires(String expires) {
            if (expires == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "expires");
            }
            this.expires = expires;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastUsed(String lastUsed) {
            if (lastUsed == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "lastUsed");
            }
            this.lastUsed = lastUsed;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder revoked(Boolean revoked) {
            if (revoked == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "revoked");
            }
            this.revoked = revoked;
            return this;
        }
        @CustomType.Setter
        public Builder state(String state) {
            if (state == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "state");
            }
            this.state = state;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(String updatedAt) {
            if (updatedAt == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "updatedAt");
            }
            this.updatedAt = updatedAt;
            return this;
        }
        @CustomType.Setter
        public Builder usageLimit(Integer usageLimit) {
            if (usageLimit == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "usageLimit");
            }
            this.usageLimit = usageLimit;
            return this;
        }
        @CustomType.Setter
        public Builder usedTimes(Integer usedTimes) {
            if (usedTimes == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "usedTimes");
            }
            this.usedTimes = usedTimes;
            return this;
        }
        @CustomType.Setter
        public Builder valid(Boolean valid) {
            if (valid == null) {
              throw new MissingRequiredPropertyException("GetSetupKeyResult", "valid");
            }
            this.valid = valid;
            return this;
        }
        public GetSetupKeyResult build() {
            final var _resultValue = new GetSetupKeyResult();
            _resultValue.allowExtraDnsLabels = allowExtraDnsLabels;
            _resultValue.autoGroups = autoGroups;
            _resultValue.ephemeral = ephemeral;
            _resultValue.expires = expires;
            _resultValue.id = id;
            _resultValue.lastUsed = lastUsed;
            _resultValue.name = name;
            _resultValue.revoked = revoked;
            _resultValue.state = state;
            _resultValue.type = type;
            _resultValue.updatedAt = updatedAt;
            _resultValue.usageLimit = usageLimit;
            _resultValue.usedTimes = usedTimes;
            _resultValue.valid = valid;
            return _resultValue;
        }
    }
}
