// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTokenResult {
    private String createdAt;
    private String expirationDate;
    private String id;
    private String lastUsed;
    private String name;
    private String userId;

    private GetTokenResult() {}
    public String createdAt() {
        return this.createdAt;
    }
    public String expirationDate() {
        return this.expirationDate;
    }
    public String id() {
        return this.id;
    }
    public String lastUsed() {
        return this.lastUsed;
    }
    public String name() {
        return this.name;
    }
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTokenResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createdAt;
        private String expirationDate;
        private String id;
        private String lastUsed;
        private String name;
        private String userId;
        public Builder() {}
        public Builder(GetTokenResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdAt = defaults.createdAt;
    	      this.expirationDate = defaults.expirationDate;
    	      this.id = defaults.id;
    	      this.lastUsed = defaults.lastUsed;
    	      this.name = defaults.name;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "createdAt");
            }
            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder expirationDate(String expirationDate) {
            if (expirationDate == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "expirationDate");
            }
            this.expirationDate = expirationDate;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastUsed(String lastUsed) {
            if (lastUsed == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "lastUsed");
            }
            this.lastUsed = lastUsed;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder userId(String userId) {
            if (userId == null) {
              throw new MissingRequiredPropertyException("GetTokenResult", "userId");
            }
            this.userId = userId;
            return this;
        }
        public GetTokenResult build() {
            final var _resultValue = new GetTokenResult();
            _resultValue.createdAt = createdAt;
            _resultValue.expirationDate = expirationDate;
            _resultValue.id = id;
            _resultValue.lastUsed = lastUsed;
            _resultValue.name = name;
            _resultValue.userId = userId;
            return _resultValue;
        }
    }
}
