// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetUserResult {
    private List<String> autoGroups;
    private String email;
    private String id;
    private Boolean isBlocked;
    private Boolean isCurrent;
    private Boolean isServiceUser;
    private String issued;
    private String lastLogin;
    private String name;
    private String role;
    private String status;

    private GetUserResult() {}
    public List<String> autoGroups() {
        return this.autoGroups;
    }
    public String email() {
        return this.email;
    }
    public String id() {
        return this.id;
    }
    public Boolean isBlocked() {
        return this.isBlocked;
    }
    public Boolean isCurrent() {
        return this.isCurrent;
    }
    public Boolean isServiceUser() {
        return this.isServiceUser;
    }
    public String issued() {
        return this.issued;
    }
    public String lastLogin() {
        return this.lastLogin;
    }
    public String name() {
        return this.name;
    }
    public String role() {
        return this.role;
    }
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUserResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> autoGroups;
        private String email;
        private String id;
        private Boolean isBlocked;
        private Boolean isCurrent;
        private Boolean isServiceUser;
        private String issued;
        private String lastLogin;
        private String name;
        private String role;
        private String status;
        public Builder() {}
        public Builder(GetUserResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.autoGroups = defaults.autoGroups;
    	      this.email = defaults.email;
    	      this.id = defaults.id;
    	      this.isBlocked = defaults.isBlocked;
    	      this.isCurrent = defaults.isCurrent;
    	      this.isServiceUser = defaults.isServiceUser;
    	      this.issued = defaults.issued;
    	      this.lastLogin = defaults.lastLogin;
    	      this.name = defaults.name;
    	      this.role = defaults.role;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder autoGroups(List<String> autoGroups) {
            if (autoGroups == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "autoGroups");
            }
            this.autoGroups = autoGroups;
            return this;
        }
        public Builder autoGroups(String... autoGroups) {
            return autoGroups(List.of(autoGroups));
        }
        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder isBlocked(Boolean isBlocked) {
            if (isBlocked == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "isBlocked");
            }
            this.isBlocked = isBlocked;
            return this;
        }
        @CustomType.Setter
        public Builder isCurrent(Boolean isCurrent) {
            if (isCurrent == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "isCurrent");
            }
            this.isCurrent = isCurrent;
            return this;
        }
        @CustomType.Setter
        public Builder isServiceUser(Boolean isServiceUser) {
            if (isServiceUser == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "isServiceUser");
            }
            this.isServiceUser = isServiceUser;
            return this;
        }
        @CustomType.Setter
        public Builder issued(String issued) {
            if (issued == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "issued");
            }
            this.issued = issued;
            return this;
        }
        @CustomType.Setter
        public Builder lastLogin(String lastLogin) {
            if (lastLogin == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "lastLogin");
            }
            this.lastLogin = lastLogin;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetUserResult", "status");
            }
            this.status = status;
            return this;
        }
        public GetUserResult build() {
            final var _resultValue = new GetUserResult();
            _resultValue.autoGroups = autoGroups;
            _resultValue.email = email;
            _resultValue.id = id;
            _resultValue.isBlocked = isBlocked;
            _resultValue.isCurrent = isCurrent;
            _resultValue.isServiceUser = isServiceUser;
            _resultValue.issued = issued;
            _resultValue.lastLogin = lastLogin;
            _resultValue.name = name;
            _resultValue.role = role;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
