// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNetworkResourceResult {
    private String address;
    private String description;
    private Boolean enabled;
    private List<String> groups;
    private String id;
    private String name;
    private String networkId;

    private GetNetworkResourceResult() {}
    public String address() {
        return this.address;
    }
    public String description() {
        return this.description;
    }
    public Boolean enabled() {
        return this.enabled;
    }
    public List<String> groups() {
        return this.groups;
    }
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String networkId() {
        return this.networkId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkResourceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String address;
        private String description;
        private Boolean enabled;
        private List<String> groups;
        private String id;
        private String name;
        private String networkId;
        public Builder() {}
        public Builder(GetNetworkResourceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.description = defaults.description;
    	      this.enabled = defaults.enabled;
    	      this.groups = defaults.groups;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.networkId = defaults.networkId;
        }

        @CustomType.Setter
        public Builder address(String address) {
            if (address == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "address");
            }
            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder groups(List<String> groups) {
            if (groups == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "groups");
            }
            this.groups = groups;
            return this;
        }
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(String networkId) {
            if (networkId == null) {
              throw new MissingRequiredPropertyException("GetNetworkResourceResult", "networkId");
            }
            this.networkId = networkId;
            return this;
        }
        public GetNetworkResourceResult build() {
            final var _resultValue = new GetNetworkResourceResult();
            _resultValue.address = address;
            _resultValue.description = description;
            _resultValue.enabled = enabled;
            _resultValue.groups = groups;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.networkId = networkId;
            return _resultValue;
        }
    }
}
