// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPolicyRuleDestinationResource {
    private String id;
    private String type;

    private GetPolicyRuleDestinationResource() {}
    public String id() {
        return this.id;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPolicyRuleDestinationResource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String type;
        public Builder() {}
        public Builder(GetPolicyRuleDestinationResource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetPolicyRuleDestinationResource", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetPolicyRuleDestinationResource", "type");
            }
            this.type = type;
            return this;
        }
        public GetPolicyRuleDestinationResource build() {
            final var _resultValue = new GetPolicyRuleDestinationResource();
            _resultValue.id = id;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
