// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NameserverGroupNameserver {
    /**
     * @return Nameserver IP
     * 
     */
    private String ip;
    /**
     * @return Nameserver Type
     * 
     */
    private @Nullable String nsType;
    /**
     * @return Nameserver Port
     * 
     */
    private @Nullable Integer port;

    private NameserverGroupNameserver() {}
    /**
     * @return Nameserver IP
     * 
     */
    public String ip() {
        return this.ip;
    }
    /**
     * @return Nameserver Type
     * 
     */
    public Optional<String> nsType() {
        return Optional.ofNullable(this.nsType);
    }
    /**
     * @return Nameserver Port
     * 
     */
    public Optional<Integer> port() {
        return Optional.ofNullable(this.port);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NameserverGroupNameserver defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ip;
        private @Nullable String nsType;
        private @Nullable Integer port;
        public Builder() {}
        public Builder(NameserverGroupNameserver defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ip = defaults.ip;
    	      this.nsType = defaults.nsType;
    	      this.port = defaults.port;
        }

        @CustomType.Setter
        public Builder ip(String ip) {
            if (ip == null) {
              throw new MissingRequiredPropertyException("NameserverGroupNameserver", "ip");
            }
            this.ip = ip;
            return this;
        }
        @CustomType.Setter
        public Builder nsType(@Nullable String nsType) {

            this.nsType = nsType;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable Integer port) {

            this.port = port;
            return this;
        }
        public NameserverGroupNameserver build() {
            final var _resultValue = new NameserverGroupNameserver();
            _resultValue.ip = ip;
            _resultValue.nsType = nsType;
            _resultValue.port = port;
            return _resultValue;
        }
    }
}
