// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ReverseProxyServiceTarget {
    /**
     * @return Whether this target is enabled
     * 
     */
    private @Nullable Boolean enabled;
    /**
     * @return Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
     * 
     */
    private @Nullable String host;
    /**
     * @return URL path prefix for this target. Defaults to &#34;/&#34; if omitted.
     * 
     */
    private @Nullable String path;
    /**
     * @return Backend port for this target (0 for scheme default)
     * 
     */
    private Integer port;
    /**
     * @return Protocol to use when connecting to the backend (http, https)
     * 
     */
    private String protocol;
    /**
     * @return Target ID (resource or peer ID)
     * 
     */
    private String targetId;
    /**
     * @return Target type (peer, host, domain, subnet)
     * 
     */
    private String targetType;

    private ReverseProxyServiceTarget() {}
    /**
     * @return Whether this target is enabled
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    /**
     * @return Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
     * 
     */
    public Optional<String> host() {
        return Optional.ofNullable(this.host);
    }
    /**
     * @return URL path prefix for this target. Defaults to &#34;/&#34; if omitted.
     * 
     */
    public Optional<String> path() {
        return Optional.ofNullable(this.path);
    }
    /**
     * @return Backend port for this target (0 for scheme default)
     * 
     */
    public Integer port() {
        return this.port;
    }
    /**
     * @return Protocol to use when connecting to the backend (http, https)
     * 
     */
    public String protocol() {
        return this.protocol;
    }
    /**
     * @return Target ID (resource or peer ID)
     * 
     */
    public String targetId() {
        return this.targetId;
    }
    /**
     * @return Target type (peer, host, domain, subnet)
     * 
     */
    public String targetType() {
        return this.targetType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ReverseProxyServiceTarget defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private @Nullable String host;
        private @Nullable String path;
        private Integer port;
        private String protocol;
        private String targetId;
        private String targetType;
        public Builder() {}
        public Builder(ReverseProxyServiceTarget defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.host = defaults.host;
    	      this.path = defaults.path;
    	      this.port = defaults.port;
    	      this.protocol = defaults.protocol;
    	      this.targetId = defaults.targetId;
    	      this.targetType = defaults.targetType;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder host(@Nullable String host) {

            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder path(@Nullable String path) {

            this.path = path;
            return this;
        }
        @CustomType.Setter
        public Builder port(Integer port) {
            if (port == null) {
              throw new MissingRequiredPropertyException("ReverseProxyServiceTarget", "port");
            }
            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(String protocol) {
            if (protocol == null) {
              throw new MissingRequiredPropertyException("ReverseProxyServiceTarget", "protocol");
            }
            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder targetId(String targetId) {
            if (targetId == null) {
              throw new MissingRequiredPropertyException("ReverseProxyServiceTarget", "targetId");
            }
            this.targetId = targetId;
            return this;
        }
        @CustomType.Setter
        public Builder targetType(String targetType) {
            if (targetType == null) {
              throw new MissingRequiredPropertyException("ReverseProxyServiceTarget", "targetType");
            }
            this.targetType = targetType;
            return this;
        }
        public ReverseProxyServiceTarget build() {
            final var _resultValue = new ReverseProxyServiceTarget();
            _resultValue.enabled = enabled;
            _resultValue.host = host;
            _resultValue.path = path;
            _resultValue.port = port;
            _resultValue.protocol = protocol;
            _resultValue.targetId = targetId;
            _resultValue.targetType = targetType;
            return _resultValue;
        }
    }
}
