// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.kitstream.netbird.AccountSettingsArgs;
import io.github.kitstream.netbird.Utilities;
import io.github.kitstream.netbird.inputs.AccountSettingsState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="netbird:index/accountSettings:AccountSettings")
public class AccountSettings extends com.pulumi.resources.CustomResource {
    /**
     * Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    @Export(name="groupsPropagationEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> groupsPropagationEnabled;

    /**
     * @return Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    public Output<Boolean> groupsPropagationEnabled() {
        return this.groupsPropagationEnabled;
    }
    /**
     * List of groups to which users are allowed access
     * 
     */
    @Export(name="jwtAllowGroups", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> jwtAllowGroups;

    /**
     * @return List of groups to which users are allowed access
     * 
     */
    public Output<List<String>> jwtAllowGroups() {
        return this.jwtAllowGroups;
    }
    /**
     * Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    @Export(name="jwtGroupsClaimName", refs={String.class}, tree="[0]")
    private Output<String> jwtGroupsClaimName;

    /**
     * @return Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    public Output<String> jwtGroupsClaimName() {
        return this.jwtGroupsClaimName;
    }
    /**
     * Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    @Export(name="jwtGroupsEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> jwtGroupsEnabled;

    /**
     * @return Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    public Output<Boolean> jwtGroupsEnabled() {
        return this.jwtGroupsEnabled;
    }
    /**
     * Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    @Export(name="networkTrafficLogsEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> networkTrafficLogsEnabled;

    /**
     * @return Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    public Output<Boolean> networkTrafficLogsEnabled() {
        return this.networkTrafficLogsEnabled;
    }
    /**
     * Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    @Export(name="networkTrafficPacketCounterEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> networkTrafficPacketCounterEnabled;

    /**
     * @return Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    public Output<Boolean> networkTrafficPacketCounterEnabled() {
        return this.networkTrafficPacketCounterEnabled;
    }
    /**
     * (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    @Export(name="peerApprovalEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> peerApprovalEnabled;

    /**
     * @return (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    public Output<Boolean> peerApprovalEnabled() {
        return this.peerApprovalEnabled;
    }
    /**
     * Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    @Export(name="peerInactivityExpiration", refs={Integer.class}, tree="[0]")
    private Output<Integer> peerInactivityExpiration;

    /**
     * @return Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    public Output<Integer> peerInactivityExpiration() {
        return this.peerInactivityExpiration;
    }
    /**
     * Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Export(name="peerInactivityExpirationEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> peerInactivityExpirationEnabled;

    /**
     * @return Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Output<Boolean> peerInactivityExpirationEnabled() {
        return this.peerInactivityExpirationEnabled;
    }
    /**
     * Period of time after which peer login expires (seconds).
     * 
     */
    @Export(name="peerLoginExpiration", refs={Integer.class}, tree="[0]")
    private Output<Integer> peerLoginExpiration;

    /**
     * @return Period of time after which peer login expires (seconds).
     * 
     */
    public Output<Integer> peerLoginExpiration() {
        return this.peerLoginExpiration;
    }
    /**
     * Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Export(name="peerLoginExpirationEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> peerLoginExpirationEnabled;

    /**
     * @return Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Output<Boolean> peerLoginExpirationEnabled() {
        return this.peerLoginExpirationEnabled;
    }
    /**
     * Allows blocking regular users from viewing parts of the system.
     * 
     */
    @Export(name="regularUsersViewBlocked", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> regularUsersViewBlocked;

    /**
     * @return Allows blocking regular users from viewing parts of the system.
     * 
     */
    public Output<Boolean> regularUsersViewBlocked() {
        return this.regularUsersViewBlocked;
    }
    /**
     * Enables or disables DNS resolution on the routing peers
     * 
     */
    @Export(name="routingPeerDnsResolutionEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> routingPeerDnsResolutionEnabled;

    /**
     * @return Enables or disables DNS resolution on the routing peers
     * 
     */
    public Output<Boolean> routingPeerDnsResolutionEnabled() {
        return this.routingPeerDnsResolutionEnabled;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AccountSettings(java.lang.String name) {
        this(name, AccountSettingsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AccountSettings(java.lang.String name, @Nullable AccountSettingsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AccountSettings(java.lang.String name, @Nullable AccountSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/accountSettings:AccountSettings", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AccountSettings(java.lang.String name, Output<java.lang.String> id, @Nullable AccountSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/accountSettings:AccountSettings", name, state, makeResourceOptions(options, id), false);
    }

    private static AccountSettingsArgs makeArgs(@Nullable AccountSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AccountSettingsArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/KitStream/netbird-pulumi-provider")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AccountSettings get(java.lang.String name, Output<java.lang.String> id, @Nullable AccountSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AccountSettings(name, id, state, options);
    }
}
