// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountSettingsArgs Empty = new AccountSettingsArgs();

    /**
     * Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    @Import(name="groupsPropagationEnabled")
    private @Nullable Output<Boolean> groupsPropagationEnabled;

    /**
     * @return Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    public Optional<Output<Boolean>> groupsPropagationEnabled() {
        return Optional.ofNullable(this.groupsPropagationEnabled);
    }

    /**
     * List of groups to which users are allowed access
     * 
     */
    @Import(name="jwtAllowGroups")
    private @Nullable Output<List<String>> jwtAllowGroups;

    /**
     * @return List of groups to which users are allowed access
     * 
     */
    public Optional<Output<List<String>>> jwtAllowGroups() {
        return Optional.ofNullable(this.jwtAllowGroups);
    }

    /**
     * Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    @Import(name="jwtGroupsClaimName")
    private @Nullable Output<String> jwtGroupsClaimName;

    /**
     * @return Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    public Optional<Output<String>> jwtGroupsClaimName() {
        return Optional.ofNullable(this.jwtGroupsClaimName);
    }

    /**
     * Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    @Import(name="jwtGroupsEnabled")
    private @Nullable Output<Boolean> jwtGroupsEnabled;

    /**
     * @return Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    public Optional<Output<Boolean>> jwtGroupsEnabled() {
        return Optional.ofNullable(this.jwtGroupsEnabled);
    }

    /**
     * Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    @Import(name="networkTrafficLogsEnabled")
    private @Nullable Output<Boolean> networkTrafficLogsEnabled;

    /**
     * @return Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    public Optional<Output<Boolean>> networkTrafficLogsEnabled() {
        return Optional.ofNullable(this.networkTrafficLogsEnabled);
    }

    /**
     * Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    @Import(name="networkTrafficPacketCounterEnabled")
    private @Nullable Output<Boolean> networkTrafficPacketCounterEnabled;

    /**
     * @return Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    public Optional<Output<Boolean>> networkTrafficPacketCounterEnabled() {
        return Optional.ofNullable(this.networkTrafficPacketCounterEnabled);
    }

    /**
     * (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    @Import(name="peerApprovalEnabled")
    private @Nullable Output<Boolean> peerApprovalEnabled;

    /**
     * @return (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    public Optional<Output<Boolean>> peerApprovalEnabled() {
        return Optional.ofNullable(this.peerApprovalEnabled);
    }

    /**
     * Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    @Import(name="peerInactivityExpiration")
    private @Nullable Output<Integer> peerInactivityExpiration;

    /**
     * @return Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    public Optional<Output<Integer>> peerInactivityExpiration() {
        return Optional.ofNullable(this.peerInactivityExpiration);
    }

    /**
     * Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Import(name="peerInactivityExpirationEnabled")
    private @Nullable Output<Boolean> peerInactivityExpirationEnabled;

    /**
     * @return Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Optional<Output<Boolean>> peerInactivityExpirationEnabled() {
        return Optional.ofNullable(this.peerInactivityExpirationEnabled);
    }

    /**
     * Period of time after which peer login expires (seconds).
     * 
     */
    @Import(name="peerLoginExpiration")
    private @Nullable Output<Integer> peerLoginExpiration;

    /**
     * @return Period of time after which peer login expires (seconds).
     * 
     */
    public Optional<Output<Integer>> peerLoginExpiration() {
        return Optional.ofNullable(this.peerLoginExpiration);
    }

    /**
     * Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Import(name="peerLoginExpirationEnabled")
    private @Nullable Output<Boolean> peerLoginExpirationEnabled;

    /**
     * @return Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Optional<Output<Boolean>> peerLoginExpirationEnabled() {
        return Optional.ofNullable(this.peerLoginExpirationEnabled);
    }

    /**
     * Allows blocking regular users from viewing parts of the system.
     * 
     */
    @Import(name="regularUsersViewBlocked")
    private @Nullable Output<Boolean> regularUsersViewBlocked;

    /**
     * @return Allows blocking regular users from viewing parts of the system.
     * 
     */
    public Optional<Output<Boolean>> regularUsersViewBlocked() {
        return Optional.ofNullable(this.regularUsersViewBlocked);
    }

    /**
     * Enables or disables DNS resolution on the routing peers
     * 
     */
    @Import(name="routingPeerDnsResolutionEnabled")
    private @Nullable Output<Boolean> routingPeerDnsResolutionEnabled;

    /**
     * @return Enables or disables DNS resolution on the routing peers
     * 
     */
    public Optional<Output<Boolean>> routingPeerDnsResolutionEnabled() {
        return Optional.ofNullable(this.routingPeerDnsResolutionEnabled);
    }

    private AccountSettingsArgs() {}

    private AccountSettingsArgs(AccountSettingsArgs $) {
        this.groupsPropagationEnabled = $.groupsPropagationEnabled;
        this.jwtAllowGroups = $.jwtAllowGroups;
        this.jwtGroupsClaimName = $.jwtGroupsClaimName;
        this.jwtGroupsEnabled = $.jwtGroupsEnabled;
        this.networkTrafficLogsEnabled = $.networkTrafficLogsEnabled;
        this.networkTrafficPacketCounterEnabled = $.networkTrafficPacketCounterEnabled;
        this.peerApprovalEnabled = $.peerApprovalEnabled;
        this.peerInactivityExpiration = $.peerInactivityExpiration;
        this.peerInactivityExpirationEnabled = $.peerInactivityExpirationEnabled;
        this.peerLoginExpiration = $.peerLoginExpiration;
        this.peerLoginExpirationEnabled = $.peerLoginExpirationEnabled;
        this.regularUsersViewBlocked = $.regularUsersViewBlocked;
        this.routingPeerDnsResolutionEnabled = $.routingPeerDnsResolutionEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountSettingsArgs $;

        public Builder() {
            $ = new AccountSettingsArgs();
        }

        public Builder(AccountSettingsArgs defaults) {
            $ = new AccountSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param groupsPropagationEnabled Allows propagate the new user auto groups to peers that belongs to the user
         * 
         * @return builder
         * 
         */
        public Builder groupsPropagationEnabled(@Nullable Output<Boolean> groupsPropagationEnabled) {
            $.groupsPropagationEnabled = groupsPropagationEnabled;
            return this;
        }

        /**
         * @param groupsPropagationEnabled Allows propagate the new user auto groups to peers that belongs to the user
         * 
         * @return builder
         * 
         */
        public Builder groupsPropagationEnabled(Boolean groupsPropagationEnabled) {
            return groupsPropagationEnabled(Output.of(groupsPropagationEnabled));
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(@Nullable Output<List<String>> jwtAllowGroups) {
            $.jwtAllowGroups = jwtAllowGroups;
            return this;
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(List<String> jwtAllowGroups) {
            return jwtAllowGroups(Output.of(jwtAllowGroups));
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(String... jwtAllowGroups) {
            return jwtAllowGroups(List.of(jwtAllowGroups));
        }

        /**
         * @param jwtGroupsClaimName Name of the claim from which we extract groups names to add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsClaimName(@Nullable Output<String> jwtGroupsClaimName) {
            $.jwtGroupsClaimName = jwtGroupsClaimName;
            return this;
        }

        /**
         * @param jwtGroupsClaimName Name of the claim from which we extract groups names to add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsClaimName(String jwtGroupsClaimName) {
            return jwtGroupsClaimName(Output.of(jwtGroupsClaimName));
        }

        /**
         * @param jwtGroupsEnabled Allows extract groups from JWT claim and add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsEnabled(@Nullable Output<Boolean> jwtGroupsEnabled) {
            $.jwtGroupsEnabled = jwtGroupsEnabled;
            return this;
        }

        /**
         * @param jwtGroupsEnabled Allows extract groups from JWT claim and add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsEnabled(Boolean jwtGroupsEnabled) {
            return jwtGroupsEnabled(Output.of(jwtGroupsEnabled));
        }

        /**
         * @param networkTrafficLogsEnabled Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsEnabled(@Nullable Output<Boolean> networkTrafficLogsEnabled) {
            $.networkTrafficLogsEnabled = networkTrafficLogsEnabled;
            return this;
        }

        /**
         * @param networkTrafficLogsEnabled Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsEnabled(Boolean networkTrafficLogsEnabled) {
            return networkTrafficLogsEnabled(Output.of(networkTrafficLogsEnabled));
        }

        /**
         * @param networkTrafficPacketCounterEnabled Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficPacketCounterEnabled(@Nullable Output<Boolean> networkTrafficPacketCounterEnabled) {
            $.networkTrafficPacketCounterEnabled = networkTrafficPacketCounterEnabled;
            return this;
        }

        /**
         * @param networkTrafficPacketCounterEnabled Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficPacketCounterEnabled(Boolean networkTrafficPacketCounterEnabled) {
            return networkTrafficPacketCounterEnabled(Output.of(networkTrafficPacketCounterEnabled));
        }

        /**
         * @param peerApprovalEnabled (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder peerApprovalEnabled(@Nullable Output<Boolean> peerApprovalEnabled) {
            $.peerApprovalEnabled = peerApprovalEnabled;
            return this;
        }

        /**
         * @param peerApprovalEnabled (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder peerApprovalEnabled(Boolean peerApprovalEnabled) {
            return peerApprovalEnabled(Output.of(peerApprovalEnabled));
        }

        /**
         * @param peerInactivityExpiration Period of time of inactivity after which peer session expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpiration(@Nullable Output<Integer> peerInactivityExpiration) {
            $.peerInactivityExpiration = peerInactivityExpiration;
            return this;
        }

        /**
         * @param peerInactivityExpiration Period of time of inactivity after which peer session expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpiration(Integer peerInactivityExpiration) {
            return peerInactivityExpiration(Output.of(peerInactivityExpiration));
        }

        /**
         * @param peerInactivityExpirationEnabled Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpirationEnabled(@Nullable Output<Boolean> peerInactivityExpirationEnabled) {
            $.peerInactivityExpirationEnabled = peerInactivityExpirationEnabled;
            return this;
        }

        /**
         * @param peerInactivityExpirationEnabled Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpirationEnabled(Boolean peerInactivityExpirationEnabled) {
            return peerInactivityExpirationEnabled(Output.of(peerInactivityExpirationEnabled));
        }

        /**
         * @param peerLoginExpiration Period of time after which peer login expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpiration(@Nullable Output<Integer> peerLoginExpiration) {
            $.peerLoginExpiration = peerLoginExpiration;
            return this;
        }

        /**
         * @param peerLoginExpiration Period of time after which peer login expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpiration(Integer peerLoginExpiration) {
            return peerLoginExpiration(Output.of(peerLoginExpiration));
        }

        /**
         * @param peerLoginExpirationEnabled Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpirationEnabled(@Nullable Output<Boolean> peerLoginExpirationEnabled) {
            $.peerLoginExpirationEnabled = peerLoginExpirationEnabled;
            return this;
        }

        /**
         * @param peerLoginExpirationEnabled Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpirationEnabled(Boolean peerLoginExpirationEnabled) {
            return peerLoginExpirationEnabled(Output.of(peerLoginExpirationEnabled));
        }

        /**
         * @param regularUsersViewBlocked Allows blocking regular users from viewing parts of the system.
         * 
         * @return builder
         * 
         */
        public Builder regularUsersViewBlocked(@Nullable Output<Boolean> regularUsersViewBlocked) {
            $.regularUsersViewBlocked = regularUsersViewBlocked;
            return this;
        }

        /**
         * @param regularUsersViewBlocked Allows blocking regular users from viewing parts of the system.
         * 
         * @return builder
         * 
         */
        public Builder regularUsersViewBlocked(Boolean regularUsersViewBlocked) {
            return regularUsersViewBlocked(Output.of(regularUsersViewBlocked));
        }

        /**
         * @param routingPeerDnsResolutionEnabled Enables or disables DNS resolution on the routing peers
         * 
         * @return builder
         * 
         */
        public Builder routingPeerDnsResolutionEnabled(@Nullable Output<Boolean> routingPeerDnsResolutionEnabled) {
            $.routingPeerDnsResolutionEnabled = routingPeerDnsResolutionEnabled;
            return this;
        }

        /**
         * @param routingPeerDnsResolutionEnabled Enables or disables DNS resolution on the routing peers
         * 
         * @return builder
         * 
         */
        public Builder routingPeerDnsResolutionEnabled(Boolean routingPeerDnsResolutionEnabled) {
            return routingPeerDnsResolutionEnabled(Output.of(routingPeerDnsResolutionEnabled));
        }

        public AccountSettingsArgs build() {
            return $;
        }
    }

}
