// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountSettingsArgs Empty = new AccountSettingsArgs();

    /**
     * Set Clients auto-update version. &#34;latest&#34;, &#34;disabled&#34;, or a specific version (e.g &#34;0.64.5&#34;)
     * 
     */
    @Import(name="autoUpdateVersion")
    private @Nullable Output<String> autoUpdateVersion;

    /**
     * @return Set Clients auto-update version. &#34;latest&#34;, &#34;disabled&#34;, or a specific version (e.g &#34;0.64.5&#34;)
     * 
     */
    public Optional<Output<String>> autoUpdateVersion() {
        return Optional.ofNullable(this.autoUpdateVersion);
    }

    /**
     * Allows to define a custom DNS domain for the account
     * 
     */
    @Import(name="dnsDomain")
    private @Nullable Output<String> dnsDomain;

    /**
     * @return Allows to define a custom DNS domain for the account
     * 
     */
    public Optional<Output<String>> dnsDomain() {
        return Optional.ofNullable(this.dnsDomain);
    }

    /**
     * Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    @Import(name="groupsPropagationEnabled")
    private @Nullable Output<Boolean> groupsPropagationEnabled;

    /**
     * @return Allows propagate the new user auto groups to peers that belongs to the user
     * 
     */
    public Optional<Output<Boolean>> groupsPropagationEnabled() {
        return Optional.ofNullable(this.groupsPropagationEnabled);
    }

    /**
     * List of groups to which users are allowed access
     * 
     */
    @Import(name="jwtAllowGroups")
    private @Nullable Output<List<String>> jwtAllowGroups;

    /**
     * @return List of groups to which users are allowed access
     * 
     */
    public Optional<Output<List<String>>> jwtAllowGroups() {
        return Optional.ofNullable(this.jwtAllowGroups);
    }

    /**
     * Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    @Import(name="jwtGroupsClaimName")
    private @Nullable Output<String> jwtGroupsClaimName;

    /**
     * @return Name of the claim from which we extract groups names to add it to account groups.
     * 
     */
    public Optional<Output<String>> jwtGroupsClaimName() {
        return Optional.ofNullable(this.jwtGroupsClaimName);
    }

    /**
     * Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    @Import(name="jwtGroupsEnabled")
    private @Nullable Output<Boolean> jwtGroupsEnabled;

    /**
     * @return Allows extract groups from JWT claim and add it to account groups.
     * 
     */
    public Optional<Output<Boolean>> jwtGroupsEnabled() {
        return Optional.ofNullable(this.jwtGroupsEnabled);
    }

    /**
     * Enables or disables experimental lazy connection
     * 
     */
    @Import(name="lazyConnectionEnabled")
    private @Nullable Output<Boolean> lazyConnectionEnabled;

    /**
     * @return Enables or disables experimental lazy connection
     * 
     */
    public Optional<Output<Boolean>> lazyConnectionEnabled() {
        return Optional.ofNullable(this.lazyConnectionEnabled);
    }

    /**
     * Allows to define a custom network range for the account in CIDR format
     * 
     */
    @Import(name="networkRange")
    private @Nullable Output<String> networkRange;

    /**
     * @return Allows to define a custom network range for the account in CIDR format
     * 
     */
    public Optional<Output<String>> networkRange() {
        return Optional.ofNullable(this.networkRange);
    }

    /**
     * Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    @Import(name="networkTrafficLogsEnabled")
    private @Nullable Output<Boolean> networkTrafficLogsEnabled;

    /**
     * @return Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
     * 
     */
    public Optional<Output<Boolean>> networkTrafficLogsEnabled() {
        return Optional.ofNullable(this.networkTrafficLogsEnabled);
    }

    /**
     * Limits traffic logging to these groups. If unset all peers are enabled.
     * 
     */
    @Import(name="networkTrafficLogsGroups")
    private @Nullable Output<List<String>> networkTrafficLogsGroups;

    /**
     * @return Limits traffic logging to these groups. If unset all peers are enabled.
     * 
     */
    public Optional<Output<List<String>>> networkTrafficLogsGroups() {
        return Optional.ofNullable(this.networkTrafficLogsGroups);
    }

    /**
     * Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    @Import(name="networkTrafficPacketCounterEnabled")
    private @Nullable Output<Boolean> networkTrafficPacketCounterEnabled;

    /**
     * @return Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
     * 
     */
    public Optional<Output<Boolean>> networkTrafficPacketCounterEnabled() {
        return Optional.ofNullable(this.networkTrafficPacketCounterEnabled);
    }

    /**
     * (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    @Import(name="peerApprovalEnabled")
    private @Nullable Output<Boolean> peerApprovalEnabled;

    /**
     * @return (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
     * 
     */
    public Optional<Output<Boolean>> peerApprovalEnabled() {
        return Optional.ofNullable(this.peerApprovalEnabled);
    }

    /**
     * Enables or disables peer expose. If enabled, peers can expose local services through the reverse proxy using the CLI.
     * 
     */
    @Import(name="peerExposeEnabled")
    private @Nullable Output<Boolean> peerExposeEnabled;

    /**
     * @return Enables or disables peer expose. If enabled, peers can expose local services through the reverse proxy using the CLI.
     * 
     */
    public Optional<Output<Boolean>> peerExposeEnabled() {
        return Optional.ofNullable(this.peerExposeEnabled);
    }

    /**
     * Limits which peer groups are allowed to expose services. If empty, all peers are allowed when peer expose is enabled.
     * 
     */
    @Import(name="peerExposeGroups")
    private @Nullable Output<List<String>> peerExposeGroups;

    /**
     * @return Limits which peer groups are allowed to expose services. If empty, all peers are allowed when peer expose is enabled.
     * 
     */
    public Optional<Output<List<String>>> peerExposeGroups() {
        return Optional.ofNullable(this.peerExposeGroups);
    }

    /**
     * Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    @Import(name="peerInactivityExpiration")
    private @Nullable Output<Integer> peerInactivityExpiration;

    /**
     * @return Period of time of inactivity after which peer session expires (seconds).
     * 
     */
    public Optional<Output<Integer>> peerInactivityExpiration() {
        return Optional.ofNullable(this.peerInactivityExpiration);
    }

    /**
     * Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Import(name="peerInactivityExpirationEnabled")
    private @Nullable Output<Boolean> peerInactivityExpirationEnabled;

    /**
     * @return Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Optional<Output<Boolean>> peerInactivityExpirationEnabled() {
        return Optional.ofNullable(this.peerInactivityExpirationEnabled);
    }

    /**
     * Period of time after which peer login expires (seconds).
     * 
     */
    @Import(name="peerLoginExpiration")
    private @Nullable Output<Integer> peerLoginExpiration;

    /**
     * @return Period of time after which peer login expires (seconds).
     * 
     */
    public Optional<Output<Integer>> peerLoginExpiration() {
        return Optional.ofNullable(this.peerLoginExpiration);
    }

    /**
     * Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    @Import(name="peerLoginExpirationEnabled")
    private @Nullable Output<Boolean> peerLoginExpirationEnabled;

    /**
     * @return Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
     * 
     */
    public Optional<Output<Boolean>> peerLoginExpirationEnabled() {
        return Optional.ofNullable(this.peerLoginExpirationEnabled);
    }

    /**
     * Allows blocking regular users from viewing parts of the system.
     * 
     */
    @Import(name="regularUsersViewBlocked")
    private @Nullable Output<Boolean> regularUsersViewBlocked;

    /**
     * @return Allows blocking regular users from viewing parts of the system.
     * 
     */
    public Optional<Output<Boolean>> regularUsersViewBlocked() {
        return Optional.ofNullable(this.regularUsersViewBlocked);
    }

    /**
     * Enables or disables DNS resolution on the routing peers
     * 
     */
    @Import(name="routingPeerDnsResolutionEnabled")
    private @Nullable Output<Boolean> routingPeerDnsResolutionEnabled;

    /**
     * @return Enables or disables DNS resolution on the routing peers
     * 
     */
    public Optional<Output<Boolean>> routingPeerDnsResolutionEnabled() {
        return Optional.ofNullable(this.routingPeerDnsResolutionEnabled);
    }

    /**
     * Enables manual approval for new users joining via domain matching. When enabled, users are blocked with pending approval status until explicitly approved by an admin.
     * 
     */
    @Import(name="userApprovalRequired")
    private @Nullable Output<Boolean> userApprovalRequired;

    /**
     * @return Enables manual approval for new users joining via domain matching. When enabled, users are blocked with pending approval status until explicitly approved by an admin.
     * 
     */
    public Optional<Output<Boolean>> userApprovalRequired() {
        return Optional.ofNullable(this.userApprovalRequired);
    }

    private AccountSettingsArgs() {}

    private AccountSettingsArgs(AccountSettingsArgs $) {
        this.autoUpdateVersion = $.autoUpdateVersion;
        this.dnsDomain = $.dnsDomain;
        this.groupsPropagationEnabled = $.groupsPropagationEnabled;
        this.jwtAllowGroups = $.jwtAllowGroups;
        this.jwtGroupsClaimName = $.jwtGroupsClaimName;
        this.jwtGroupsEnabled = $.jwtGroupsEnabled;
        this.lazyConnectionEnabled = $.lazyConnectionEnabled;
        this.networkRange = $.networkRange;
        this.networkTrafficLogsEnabled = $.networkTrafficLogsEnabled;
        this.networkTrafficLogsGroups = $.networkTrafficLogsGroups;
        this.networkTrafficPacketCounterEnabled = $.networkTrafficPacketCounterEnabled;
        this.peerApprovalEnabled = $.peerApprovalEnabled;
        this.peerExposeEnabled = $.peerExposeEnabled;
        this.peerExposeGroups = $.peerExposeGroups;
        this.peerInactivityExpiration = $.peerInactivityExpiration;
        this.peerInactivityExpirationEnabled = $.peerInactivityExpirationEnabled;
        this.peerLoginExpiration = $.peerLoginExpiration;
        this.peerLoginExpirationEnabled = $.peerLoginExpirationEnabled;
        this.regularUsersViewBlocked = $.regularUsersViewBlocked;
        this.routingPeerDnsResolutionEnabled = $.routingPeerDnsResolutionEnabled;
        this.userApprovalRequired = $.userApprovalRequired;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountSettingsArgs $;

        public Builder() {
            $ = new AccountSettingsArgs();
        }

        public Builder(AccountSettingsArgs defaults) {
            $ = new AccountSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autoUpdateVersion Set Clients auto-update version. &#34;latest&#34;, &#34;disabled&#34;, or a specific version (e.g &#34;0.64.5&#34;)
         * 
         * @return builder
         * 
         */
        public Builder autoUpdateVersion(@Nullable Output<String> autoUpdateVersion) {
            $.autoUpdateVersion = autoUpdateVersion;
            return this;
        }

        /**
         * @param autoUpdateVersion Set Clients auto-update version. &#34;latest&#34;, &#34;disabled&#34;, or a specific version (e.g &#34;0.64.5&#34;)
         * 
         * @return builder
         * 
         */
        public Builder autoUpdateVersion(String autoUpdateVersion) {
            return autoUpdateVersion(Output.of(autoUpdateVersion));
        }

        /**
         * @param dnsDomain Allows to define a custom DNS domain for the account
         * 
         * @return builder
         * 
         */
        public Builder dnsDomain(@Nullable Output<String> dnsDomain) {
            $.dnsDomain = dnsDomain;
            return this;
        }

        /**
         * @param dnsDomain Allows to define a custom DNS domain for the account
         * 
         * @return builder
         * 
         */
        public Builder dnsDomain(String dnsDomain) {
            return dnsDomain(Output.of(dnsDomain));
        }

        /**
         * @param groupsPropagationEnabled Allows propagate the new user auto groups to peers that belongs to the user
         * 
         * @return builder
         * 
         */
        public Builder groupsPropagationEnabled(@Nullable Output<Boolean> groupsPropagationEnabled) {
            $.groupsPropagationEnabled = groupsPropagationEnabled;
            return this;
        }

        /**
         * @param groupsPropagationEnabled Allows propagate the new user auto groups to peers that belongs to the user
         * 
         * @return builder
         * 
         */
        public Builder groupsPropagationEnabled(Boolean groupsPropagationEnabled) {
            return groupsPropagationEnabled(Output.of(groupsPropagationEnabled));
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(@Nullable Output<List<String>> jwtAllowGroups) {
            $.jwtAllowGroups = jwtAllowGroups;
            return this;
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(List<String> jwtAllowGroups) {
            return jwtAllowGroups(Output.of(jwtAllowGroups));
        }

        /**
         * @param jwtAllowGroups List of groups to which users are allowed access
         * 
         * @return builder
         * 
         */
        public Builder jwtAllowGroups(String... jwtAllowGroups) {
            return jwtAllowGroups(List.of(jwtAllowGroups));
        }

        /**
         * @param jwtGroupsClaimName Name of the claim from which we extract groups names to add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsClaimName(@Nullable Output<String> jwtGroupsClaimName) {
            $.jwtGroupsClaimName = jwtGroupsClaimName;
            return this;
        }

        /**
         * @param jwtGroupsClaimName Name of the claim from which we extract groups names to add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsClaimName(String jwtGroupsClaimName) {
            return jwtGroupsClaimName(Output.of(jwtGroupsClaimName));
        }

        /**
         * @param jwtGroupsEnabled Allows extract groups from JWT claim and add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsEnabled(@Nullable Output<Boolean> jwtGroupsEnabled) {
            $.jwtGroupsEnabled = jwtGroupsEnabled;
            return this;
        }

        /**
         * @param jwtGroupsEnabled Allows extract groups from JWT claim and add it to account groups.
         * 
         * @return builder
         * 
         */
        public Builder jwtGroupsEnabled(Boolean jwtGroupsEnabled) {
            return jwtGroupsEnabled(Output.of(jwtGroupsEnabled));
        }

        /**
         * @param lazyConnectionEnabled Enables or disables experimental lazy connection
         * 
         * @return builder
         * 
         */
        public Builder lazyConnectionEnabled(@Nullable Output<Boolean> lazyConnectionEnabled) {
            $.lazyConnectionEnabled = lazyConnectionEnabled;
            return this;
        }

        /**
         * @param lazyConnectionEnabled Enables or disables experimental lazy connection
         * 
         * @return builder
         * 
         */
        public Builder lazyConnectionEnabled(Boolean lazyConnectionEnabled) {
            return lazyConnectionEnabled(Output.of(lazyConnectionEnabled));
        }

        /**
         * @param networkRange Allows to define a custom network range for the account in CIDR format
         * 
         * @return builder
         * 
         */
        public Builder networkRange(@Nullable Output<String> networkRange) {
            $.networkRange = networkRange;
            return this;
        }

        /**
         * @param networkRange Allows to define a custom network range for the account in CIDR format
         * 
         * @return builder
         * 
         */
        public Builder networkRange(String networkRange) {
            return networkRange(Output.of(networkRange));
        }

        /**
         * @param networkTrafficLogsEnabled Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsEnabled(@Nullable Output<Boolean> networkTrafficLogsEnabled) {
            $.networkTrafficLogsEnabled = networkTrafficLogsEnabled;
            return this;
        }

        /**
         * @param networkTrafficLogsEnabled Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsEnabled(Boolean networkTrafficLogsEnabled) {
            return networkTrafficLogsEnabled(Output.of(networkTrafficLogsEnabled));
        }

        /**
         * @param networkTrafficLogsGroups Limits traffic logging to these groups. If unset all peers are enabled.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsGroups(@Nullable Output<List<String>> networkTrafficLogsGroups) {
            $.networkTrafficLogsGroups = networkTrafficLogsGroups;
            return this;
        }

        /**
         * @param networkTrafficLogsGroups Limits traffic logging to these groups. If unset all peers are enabled.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsGroups(List<String> networkTrafficLogsGroups) {
            return networkTrafficLogsGroups(Output.of(networkTrafficLogsGroups));
        }

        /**
         * @param networkTrafficLogsGroups Limits traffic logging to these groups. If unset all peers are enabled.
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficLogsGroups(String... networkTrafficLogsGroups) {
            return networkTrafficLogsGroups(List.of(networkTrafficLogsGroups));
        }

        /**
         * @param networkTrafficPacketCounterEnabled Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficPacketCounterEnabled(@Nullable Output<Boolean> networkTrafficPacketCounterEnabled) {
            $.networkTrafficPacketCounterEnabled = networkTrafficPacketCounterEnabled;
            return this;
        }

        /**
         * @param networkTrafficPacketCounterEnabled Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
         * 
         * @return builder
         * 
         */
        public Builder networkTrafficPacketCounterEnabled(Boolean networkTrafficPacketCounterEnabled) {
            return networkTrafficPacketCounterEnabled(Output.of(networkTrafficPacketCounterEnabled));
        }

        /**
         * @param peerApprovalEnabled (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder peerApprovalEnabled(@Nullable Output<Boolean> peerApprovalEnabled) {
            $.peerApprovalEnabled = peerApprovalEnabled;
            return this;
        }

        /**
         * @param peerApprovalEnabled (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder peerApprovalEnabled(Boolean peerApprovalEnabled) {
            return peerApprovalEnabled(Output.of(peerApprovalEnabled));
        }

        /**
         * @param peerExposeEnabled Enables or disables peer expose. If enabled, peers can expose local services through the reverse proxy using the CLI.
         * 
         * @return builder
         * 
         */
        public Builder peerExposeEnabled(@Nullable Output<Boolean> peerExposeEnabled) {
            $.peerExposeEnabled = peerExposeEnabled;
            return this;
        }

        /**
         * @param peerExposeEnabled Enables or disables peer expose. If enabled, peers can expose local services through the reverse proxy using the CLI.
         * 
         * @return builder
         * 
         */
        public Builder peerExposeEnabled(Boolean peerExposeEnabled) {
            return peerExposeEnabled(Output.of(peerExposeEnabled));
        }

        /**
         * @param peerExposeGroups Limits which peer groups are allowed to expose services. If empty, all peers are allowed when peer expose is enabled.
         * 
         * @return builder
         * 
         */
        public Builder peerExposeGroups(@Nullable Output<List<String>> peerExposeGroups) {
            $.peerExposeGroups = peerExposeGroups;
            return this;
        }

        /**
         * @param peerExposeGroups Limits which peer groups are allowed to expose services. If empty, all peers are allowed when peer expose is enabled.
         * 
         * @return builder
         * 
         */
        public Builder peerExposeGroups(List<String> peerExposeGroups) {
            return peerExposeGroups(Output.of(peerExposeGroups));
        }

        /**
         * @param peerExposeGroups Limits which peer groups are allowed to expose services. If empty, all peers are allowed when peer expose is enabled.
         * 
         * @return builder
         * 
         */
        public Builder peerExposeGroups(String... peerExposeGroups) {
            return peerExposeGroups(List.of(peerExposeGroups));
        }

        /**
         * @param peerInactivityExpiration Period of time of inactivity after which peer session expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpiration(@Nullable Output<Integer> peerInactivityExpiration) {
            $.peerInactivityExpiration = peerInactivityExpiration;
            return this;
        }

        /**
         * @param peerInactivityExpiration Period of time of inactivity after which peer session expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpiration(Integer peerInactivityExpiration) {
            return peerInactivityExpiration(Output.of(peerInactivityExpiration));
        }

        /**
         * @param peerInactivityExpirationEnabled Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpirationEnabled(@Nullable Output<Boolean> peerInactivityExpirationEnabled) {
            $.peerInactivityExpirationEnabled = peerInactivityExpirationEnabled;
            return this;
        }

        /**
         * @param peerInactivityExpirationEnabled Enables or disables peer inactivity expiration globally. After peer&#39;s session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerInactivityExpirationEnabled(Boolean peerInactivityExpirationEnabled) {
            return peerInactivityExpirationEnabled(Output.of(peerInactivityExpirationEnabled));
        }

        /**
         * @param peerLoginExpiration Period of time after which peer login expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpiration(@Nullable Output<Integer> peerLoginExpiration) {
            $.peerLoginExpiration = peerLoginExpiration;
            return this;
        }

        /**
         * @param peerLoginExpiration Period of time after which peer login expires (seconds).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpiration(Integer peerLoginExpiration) {
            return peerLoginExpiration(Output.of(peerLoginExpiration));
        }

        /**
         * @param peerLoginExpirationEnabled Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpirationEnabled(@Nullable Output<Boolean> peerLoginExpirationEnabled) {
            $.peerLoginExpirationEnabled = peerLoginExpirationEnabled;
            return this;
        }

        /**
         * @param peerLoginExpirationEnabled Enables or disables peer login expiration globally. After peer&#39;s login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
         * 
         * @return builder
         * 
         */
        public Builder peerLoginExpirationEnabled(Boolean peerLoginExpirationEnabled) {
            return peerLoginExpirationEnabled(Output.of(peerLoginExpirationEnabled));
        }

        /**
         * @param regularUsersViewBlocked Allows blocking regular users from viewing parts of the system.
         * 
         * @return builder
         * 
         */
        public Builder regularUsersViewBlocked(@Nullable Output<Boolean> regularUsersViewBlocked) {
            $.regularUsersViewBlocked = regularUsersViewBlocked;
            return this;
        }

        /**
         * @param regularUsersViewBlocked Allows blocking regular users from viewing parts of the system.
         * 
         * @return builder
         * 
         */
        public Builder regularUsersViewBlocked(Boolean regularUsersViewBlocked) {
            return regularUsersViewBlocked(Output.of(regularUsersViewBlocked));
        }

        /**
         * @param routingPeerDnsResolutionEnabled Enables or disables DNS resolution on the routing peers
         * 
         * @return builder
         * 
         */
        public Builder routingPeerDnsResolutionEnabled(@Nullable Output<Boolean> routingPeerDnsResolutionEnabled) {
            $.routingPeerDnsResolutionEnabled = routingPeerDnsResolutionEnabled;
            return this;
        }

        /**
         * @param routingPeerDnsResolutionEnabled Enables or disables DNS resolution on the routing peers
         * 
         * @return builder
         * 
         */
        public Builder routingPeerDnsResolutionEnabled(Boolean routingPeerDnsResolutionEnabled) {
            return routingPeerDnsResolutionEnabled(Output.of(routingPeerDnsResolutionEnabled));
        }

        /**
         * @param userApprovalRequired Enables manual approval for new users joining via domain matching. When enabled, users are blocked with pending approval status until explicitly approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder userApprovalRequired(@Nullable Output<Boolean> userApprovalRequired) {
            $.userApprovalRequired = userApprovalRequired;
            return this;
        }

        /**
         * @param userApprovalRequired Enables manual approval for new users joining via domain matching. When enabled, users are blocked with pending approval status until explicitly approved by an admin.
         * 
         * @return builder
         * 
         */
        public Builder userApprovalRequired(Boolean userApprovalRequired) {
            return userApprovalRequired(Output.of(userApprovalRequired));
        }

        public AccountSettingsArgs build() {
            return $;
        }
    }

}
