// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DnsZoneArgs extends com.pulumi.resources.ResourceArgs {

    public static final DnsZoneArgs Empty = new DnsZoneArgs();

    /**
     * Group IDs that define groups of peers that will resolve this zone
     * 
     */
    @Import(name="distributionGroups")
    private @Nullable Output<List<String>> distributionGroups;

    /**
     * @return Group IDs that define groups of peers that will resolve this zone
     * 
     */
    public Optional<Output<List<String>>> distributionGroups() {
        return Optional.ofNullable(this.distributionGroups);
    }

    /**
     * Zone domain (FQDN)
     * 
     */
    @Import(name="domain", required=true)
    private Output<String> domain;

    /**
     * @return Zone domain (FQDN)
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }

    /**
     * Enable this zone as a search domain
     * 
     */
    @Import(name="enableSearchDomain")
    private @Nullable Output<Boolean> enableSearchDomain;

    /**
     * @return Enable this zone as a search domain
     * 
     */
    public Optional<Output<Boolean>> enableSearchDomain() {
        return Optional.ofNullable(this.enableSearchDomain);
    }

    /**
     * DNS Zone status
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return DNS Zone status
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * DNS Zone name identifier
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return DNS Zone name identifier
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private DnsZoneArgs() {}

    private DnsZoneArgs(DnsZoneArgs $) {
        this.distributionGroups = $.distributionGroups;
        this.domain = $.domain;
        this.enableSearchDomain = $.enableSearchDomain;
        this.enabled = $.enabled;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DnsZoneArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DnsZoneArgs $;

        public Builder() {
            $ = new DnsZoneArgs();
        }

        public Builder(DnsZoneArgs defaults) {
            $ = new DnsZoneArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param distributionGroups Group IDs that define groups of peers that will resolve this zone
         * 
         * @return builder
         * 
         */
        public Builder distributionGroups(@Nullable Output<List<String>> distributionGroups) {
            $.distributionGroups = distributionGroups;
            return this;
        }

        /**
         * @param distributionGroups Group IDs that define groups of peers that will resolve this zone
         * 
         * @return builder
         * 
         */
        public Builder distributionGroups(List<String> distributionGroups) {
            return distributionGroups(Output.of(distributionGroups));
        }

        /**
         * @param distributionGroups Group IDs that define groups of peers that will resolve this zone
         * 
         * @return builder
         * 
         */
        public Builder distributionGroups(String... distributionGroups) {
            return distributionGroups(List.of(distributionGroups));
        }

        /**
         * @param domain Zone domain (FQDN)
         * 
         * @return builder
         * 
         */
        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain Zone domain (FQDN)
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param enableSearchDomain Enable this zone as a search domain
         * 
         * @return builder
         * 
         */
        public Builder enableSearchDomain(@Nullable Output<Boolean> enableSearchDomain) {
            $.enableSearchDomain = enableSearchDomain;
            return this;
        }

        /**
         * @param enableSearchDomain Enable this zone as a search domain
         * 
         * @return builder
         * 
         */
        public Builder enableSearchDomain(Boolean enableSearchDomain) {
            return enableSearchDomain(Output.of(enableSearchDomain));
        }

        /**
         * @param enabled DNS Zone status
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled DNS Zone status
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param name DNS Zone name identifier
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name DNS Zone name identifier
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public DnsZoneArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("DnsZoneArgs", "domain");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("DnsZoneArgs", "name");
            }
            return $;
        }
    }

}
