// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkResourceArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkResourceArgs Empty = new NetworkResourceArgs();

    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
     * 
     */
    @Import(name="address", required=true)
    private Output<String> address;

    /**
     * @return Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
     * 
     */
    public Output<String> address() {
        return this.address;
    }

    /**
     * NetworkResource Description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return NetworkResource Description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * NetworkResource status
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return NetworkResource status
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Group IDs containing the resource
     * 
     */
    @Import(name="groups", required=true)
    private Output<List<String>> groups;

    /**
     * @return Group IDs containing the resource
     * 
     */
    public Output<List<String>> groups() {
        return this.groups;
    }

    /**
     * NetworkResource Name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return NetworkResource Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The unique identifier of a network
     * 
     */
    @Import(name="networkId", required=true)
    private Output<String> networkId;

    /**
     * @return The unique identifier of a network
     * 
     */
    public Output<String> networkId() {
        return this.networkId;
    }

    private NetworkResourceArgs() {}

    private NetworkResourceArgs(NetworkResourceArgs $) {
        this.address = $.address;
        this.description = $.description;
        this.enabled = $.enabled;
        this.groups = $.groups;
        this.name = $.name;
        this.networkId = $.networkId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkResourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkResourceArgs $;

        public Builder() {
            $ = new NetworkResourceArgs();
        }

        public Builder(NetworkResourceArgs defaults) {
            $ = new NetworkResourceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param address Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
         * 
         * @return builder
         * 
         */
        public Builder address(Output<String> address) {
            $.address = address;
            return this;
        }

        /**
         * @param address Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
         * 
         * @return builder
         * 
         */
        public Builder address(String address) {
            return address(Output.of(address));
        }

        /**
         * @param description NetworkResource Description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description NetworkResource Description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enabled NetworkResource status
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled NetworkResource status
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param groups Group IDs containing the resource
         * 
         * @return builder
         * 
         */
        public Builder groups(Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        /**
         * @param groups Group IDs containing the resource
         * 
         * @return builder
         * 
         */
        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        /**
         * @param groups Group IDs containing the resource
         * 
         * @return builder
         * 
         */
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        /**
         * @param name NetworkResource Name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name NetworkResource Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param networkId The unique identifier of a network
         * 
         * @return builder
         * 
         */
        public Builder networkId(Output<String> networkId) {
            $.networkId = networkId;
            return this;
        }

        /**
         * @param networkId The unique identifier of a network
         * 
         * @return builder
         * 
         */
        public Builder networkId(String networkId) {
            return networkId(Output.of(networkId));
        }

        public NetworkResourceArgs build() {
            if ($.address == null) {
                throw new MissingRequiredPropertyException("NetworkResourceArgs", "address");
            }
            if ($.groups == null) {
                throw new MissingRequiredPropertyException("NetworkResourceArgs", "groups");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("NetworkResourceArgs", "name");
            }
            if ($.networkId == null) {
                throw new MissingRequiredPropertyException("NetworkResourceArgs", "networkId");
            }
            return $;
        }
    }

}
