// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.kitstream.netbird.inputs.PostureCheckGeoLocationCheckArgs;
import io.github.kitstream.netbird.inputs.PostureCheckNetbirdVersionCheckArgs;
import io.github.kitstream.netbird.inputs.PostureCheckOsVersionCheckArgs;
import io.github.kitstream.netbird.inputs.PostureCheckPeerNetworkRangeCheckArgs;
import io.github.kitstream.netbird.inputs.PostureCheckProcessCheckArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PostureCheckArgs extends com.pulumi.resources.ResourceArgs {

    public static final PostureCheckArgs Empty = new PostureCheckArgs();

    /**
     * PostureCheck description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return PostureCheck description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="geoLocationCheck")
    private @Nullable Output<PostureCheckGeoLocationCheckArgs> geoLocationCheck;

    public Optional<Output<PostureCheckGeoLocationCheckArgs>> geoLocationCheck() {
        return Optional.ofNullable(this.geoLocationCheck);
    }

    /**
     * PostureCheck Name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return PostureCheck Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    @Import(name="netbirdVersionCheck")
    private @Nullable Output<PostureCheckNetbirdVersionCheckArgs> netbirdVersionCheck;

    public Optional<Output<PostureCheckNetbirdVersionCheckArgs>> netbirdVersionCheck() {
        return Optional.ofNullable(this.netbirdVersionCheck);
    }

    @Import(name="osVersionCheck")
    private @Nullable Output<PostureCheckOsVersionCheckArgs> osVersionCheck;

    public Optional<Output<PostureCheckOsVersionCheckArgs>> osVersionCheck() {
        return Optional.ofNullable(this.osVersionCheck);
    }

    @Import(name="peerNetworkRangeCheck")
    private @Nullable Output<PostureCheckPeerNetworkRangeCheckArgs> peerNetworkRangeCheck;

    public Optional<Output<PostureCheckPeerNetworkRangeCheckArgs>> peerNetworkRangeCheck() {
        return Optional.ofNullable(this.peerNetworkRangeCheck);
    }

    @Import(name="processChecks")
    private @Nullable Output<List<PostureCheckProcessCheckArgs>> processChecks;

    public Optional<Output<List<PostureCheckProcessCheckArgs>>> processChecks() {
        return Optional.ofNullable(this.processChecks);
    }

    private PostureCheckArgs() {}

    private PostureCheckArgs(PostureCheckArgs $) {
        this.description = $.description;
        this.geoLocationCheck = $.geoLocationCheck;
        this.name = $.name;
        this.netbirdVersionCheck = $.netbirdVersionCheck;
        this.osVersionCheck = $.osVersionCheck;
        this.peerNetworkRangeCheck = $.peerNetworkRangeCheck;
        this.processChecks = $.processChecks;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PostureCheckArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PostureCheckArgs $;

        public Builder() {
            $ = new PostureCheckArgs();
        }

        public Builder(PostureCheckArgs defaults) {
            $ = new PostureCheckArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description PostureCheck description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description PostureCheck description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder geoLocationCheck(@Nullable Output<PostureCheckGeoLocationCheckArgs> geoLocationCheck) {
            $.geoLocationCheck = geoLocationCheck;
            return this;
        }

        public Builder geoLocationCheck(PostureCheckGeoLocationCheckArgs geoLocationCheck) {
            return geoLocationCheck(Output.of(geoLocationCheck));
        }

        /**
         * @param name PostureCheck Name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name PostureCheck Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder netbirdVersionCheck(@Nullable Output<PostureCheckNetbirdVersionCheckArgs> netbirdVersionCheck) {
            $.netbirdVersionCheck = netbirdVersionCheck;
            return this;
        }

        public Builder netbirdVersionCheck(PostureCheckNetbirdVersionCheckArgs netbirdVersionCheck) {
            return netbirdVersionCheck(Output.of(netbirdVersionCheck));
        }

        public Builder osVersionCheck(@Nullable Output<PostureCheckOsVersionCheckArgs> osVersionCheck) {
            $.osVersionCheck = osVersionCheck;
            return this;
        }

        public Builder osVersionCheck(PostureCheckOsVersionCheckArgs osVersionCheck) {
            return osVersionCheck(Output.of(osVersionCheck));
        }

        public Builder peerNetworkRangeCheck(@Nullable Output<PostureCheckPeerNetworkRangeCheckArgs> peerNetworkRangeCheck) {
            $.peerNetworkRangeCheck = peerNetworkRangeCheck;
            return this;
        }

        public Builder peerNetworkRangeCheck(PostureCheckPeerNetworkRangeCheckArgs peerNetworkRangeCheck) {
            return peerNetworkRangeCheck(Output.of(peerNetworkRangeCheck));
        }

        public Builder processChecks(@Nullable Output<List<PostureCheckProcessCheckArgs>> processChecks) {
            $.processChecks = processChecks;
            return this;
        }

        public Builder processChecks(List<PostureCheckProcessCheckArgs> processChecks) {
            return processChecks(Output.of(processChecks));
        }

        public Builder processChecks(PostureCheckProcessCheckArgs... processChecks) {
            return processChecks(List.of(processChecks));
        }

        public PostureCheckArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("PostureCheckArgs", "name");
            }
            return $;
        }
    }

}
