// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.kitstream.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RouteArgs extends com.pulumi.resources.ResourceArgs {

    public static final RouteArgs Empty = new RouteArgs();

    /**
     * Access control group identifier associated with route.
     * 
     */
    @Import(name="accessControlGroups")
    private @Nullable Output<List<String>> accessControlGroups;

    /**
     * @return Access control group identifier associated with route.
     * 
     */
    public Optional<Output<List<String>>> accessControlGroups() {
        return Optional.ofNullable(this.accessControlGroups);
    }

    /**
     * Route description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Route description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
     * 
     */
    @Import(name="domains")
    private @Nullable Output<List<String>> domains;

    /**
     * @return Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
     * 
     */
    public Optional<Output<List<String>>> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * Route status
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Route status
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Group IDs containing routing peers
     * 
     */
    @Import(name="groups", required=true)
    private Output<List<String>> groups;

    /**
     * @return Group IDs containing routing peers
     * 
     */
    public Output<List<String>> groups() {
        return this.groups;
    }

    /**
     * Indicate if the route should be kept after a domain doesn&#39;t resolve that IP anymore
     * 
     */
    @Import(name="keepRoute")
    private @Nullable Output<Boolean> keepRoute;

    /**
     * @return Indicate if the route should be kept after a domain doesn&#39;t resolve that IP anymore
     * 
     */
    public Optional<Output<Boolean>> keepRoute() {
        return Optional.ofNullable(this.keepRoute);
    }

    /**
     * Indicate if peer should masquerade traffic to this route&#39;s prefix
     * 
     */
    @Import(name="masquerade")
    private @Nullable Output<Boolean> masquerade;

    /**
     * @return Indicate if peer should masquerade traffic to this route&#39;s prefix
     * 
     */
    public Optional<Output<Boolean>> masquerade() {
        return Optional.ofNullable(this.masquerade);
    }

    /**
     * Route metric number. Lowest number has higher priority
     * 
     */
    @Import(name="metric")
    private @Nullable Output<Integer> metric;

    /**
     * @return Route metric number. Lowest number has higher priority
     * 
     */
    public Optional<Output<Integer>> metric() {
        return Optional.ofNullable(this.metric);
    }

    /**
     * Network range in CIDR format, Conflicts with domains
     * 
     */
    @Import(name="network")
    private @Nullable Output<String> network;

    /**
     * @return Network range in CIDR format, Conflicts with domains
     * 
     */
    public Optional<Output<String>> network() {
        return Optional.ofNullable(this.network);
    }

    /**
     * Route network identifier, to group HA routes
     * 
     */
    @Import(name="networkId", required=true)
    private Output<String> networkId;

    /**
     * @return Route network identifier, to group HA routes
     * 
     */
    public Output<String> networkId() {
        return this.networkId;
    }

    /**
     * Peer Identifier associated with route. This property can not be set together with peer_groups
     * 
     */
    @Import(name="peer")
    private @Nullable Output<String> peer;

    /**
     * @return Peer Identifier associated with route. This property can not be set together with peer_groups
     * 
     */
    public Optional<Output<String>> peer() {
        return Optional.ofNullable(this.peer);
    }

    /**
     * Peers Group Identifier associated with route. This property can not be set together with peer
     * 
     */
    @Import(name="peerGroups")
    private @Nullable Output<List<String>> peerGroups;

    /**
     * @return Peers Group Identifier associated with route. This property can not be set together with peer
     * 
     */
    public Optional<Output<List<String>>> peerGroups() {
        return Optional.ofNullable(this.peerGroups);
    }

    private RouteArgs() {}

    private RouteArgs(RouteArgs $) {
        this.accessControlGroups = $.accessControlGroups;
        this.description = $.description;
        this.domains = $.domains;
        this.enabled = $.enabled;
        this.groups = $.groups;
        this.keepRoute = $.keepRoute;
        this.masquerade = $.masquerade;
        this.metric = $.metric;
        this.network = $.network;
        this.networkId = $.networkId;
        this.peer = $.peer;
        this.peerGroups = $.peerGroups;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RouteArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RouteArgs $;

        public Builder() {
            $ = new RouteArgs();
        }

        public Builder(RouteArgs defaults) {
            $ = new RouteArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessControlGroups Access control group identifier associated with route.
         * 
         * @return builder
         * 
         */
        public Builder accessControlGroups(@Nullable Output<List<String>> accessControlGroups) {
            $.accessControlGroups = accessControlGroups;
            return this;
        }

        /**
         * @param accessControlGroups Access control group identifier associated with route.
         * 
         * @return builder
         * 
         */
        public Builder accessControlGroups(List<String> accessControlGroups) {
            return accessControlGroups(Output.of(accessControlGroups));
        }

        /**
         * @param accessControlGroups Access control group identifier associated with route.
         * 
         * @return builder
         * 
         */
        public Builder accessControlGroups(String... accessControlGroups) {
            return accessControlGroups(List.of(accessControlGroups));
        }

        /**
         * @param description Route description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Route description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param domains Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
         * 
         * @return builder
         * 
         */
        public Builder domains(@Nullable Output<List<String>> domains) {
            $.domains = domains;
            return this;
        }

        /**
         * @param domains Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
         * 
         * @return builder
         * 
         */
        public Builder domains(List<String> domains) {
            return domains(Output.of(domains));
        }

        /**
         * @param domains Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
         * 
         * @return builder
         * 
         */
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }

        /**
         * @param enabled Route status
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Route status
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param groups Group IDs containing routing peers
         * 
         * @return builder
         * 
         */
        public Builder groups(Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        /**
         * @param groups Group IDs containing routing peers
         * 
         * @return builder
         * 
         */
        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        /**
         * @param groups Group IDs containing routing peers
         * 
         * @return builder
         * 
         */
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        /**
         * @param keepRoute Indicate if the route should be kept after a domain doesn&#39;t resolve that IP anymore
         * 
         * @return builder
         * 
         */
        public Builder keepRoute(@Nullable Output<Boolean> keepRoute) {
            $.keepRoute = keepRoute;
            return this;
        }

        /**
         * @param keepRoute Indicate if the route should be kept after a domain doesn&#39;t resolve that IP anymore
         * 
         * @return builder
         * 
         */
        public Builder keepRoute(Boolean keepRoute) {
            return keepRoute(Output.of(keepRoute));
        }

        /**
         * @param masquerade Indicate if peer should masquerade traffic to this route&#39;s prefix
         * 
         * @return builder
         * 
         */
        public Builder masquerade(@Nullable Output<Boolean> masquerade) {
            $.masquerade = masquerade;
            return this;
        }

        /**
         * @param masquerade Indicate if peer should masquerade traffic to this route&#39;s prefix
         * 
         * @return builder
         * 
         */
        public Builder masquerade(Boolean masquerade) {
            return masquerade(Output.of(masquerade));
        }

        /**
         * @param metric Route metric number. Lowest number has higher priority
         * 
         * @return builder
         * 
         */
        public Builder metric(@Nullable Output<Integer> metric) {
            $.metric = metric;
            return this;
        }

        /**
         * @param metric Route metric number. Lowest number has higher priority
         * 
         * @return builder
         * 
         */
        public Builder metric(Integer metric) {
            return metric(Output.of(metric));
        }

        /**
         * @param network Network range in CIDR format, Conflicts with domains
         * 
         * @return builder
         * 
         */
        public Builder network(@Nullable Output<String> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network Network range in CIDR format, Conflicts with domains
         * 
         * @return builder
         * 
         */
        public Builder network(String network) {
            return network(Output.of(network));
        }

        /**
         * @param networkId Route network identifier, to group HA routes
         * 
         * @return builder
         * 
         */
        public Builder networkId(Output<String> networkId) {
            $.networkId = networkId;
            return this;
        }

        /**
         * @param networkId Route network identifier, to group HA routes
         * 
         * @return builder
         * 
         */
        public Builder networkId(String networkId) {
            return networkId(Output.of(networkId));
        }

        /**
         * @param peer Peer Identifier associated with route. This property can not be set together with peer_groups
         * 
         * @return builder
         * 
         */
        public Builder peer(@Nullable Output<String> peer) {
            $.peer = peer;
            return this;
        }

        /**
         * @param peer Peer Identifier associated with route. This property can not be set together with peer_groups
         * 
         * @return builder
         * 
         */
        public Builder peer(String peer) {
            return peer(Output.of(peer));
        }

        /**
         * @param peerGroups Peers Group Identifier associated with route. This property can not be set together with peer
         * 
         * @return builder
         * 
         */
        public Builder peerGroups(@Nullable Output<List<String>> peerGroups) {
            $.peerGroups = peerGroups;
            return this;
        }

        /**
         * @param peerGroups Peers Group Identifier associated with route. This property can not be set together with peer
         * 
         * @return builder
         * 
         */
        public Builder peerGroups(List<String> peerGroups) {
            return peerGroups(Output.of(peerGroups));
        }

        /**
         * @param peerGroups Peers Group Identifier associated with route. This property can not be set together with peer
         * 
         * @return builder
         * 
         */
        public Builder peerGroups(String... peerGroups) {
            return peerGroups(List.of(peerGroups));
        }

        public RouteArgs build() {
            if ($.groups == null) {
                throw new MissingRequiredPropertyException("RouteArgs", "groups");
            }
            if ($.networkId == null) {
                throw new MissingRequiredPropertyException("RouteArgs", "networkId");
            }
            return $;
        }
    }

}
