// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"github.com/netbirdio/pulumi-netbird/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDnsSettings(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupDnsSettingsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDnsSettingsResult
	err := ctx.Invoke("netbird:index/getDnsSettings:getDnsSettings", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDnsSettings.
type LookupDnsSettingsResult struct {
	DisabledManagementGroups []string `pulumi:"disabledManagementGroups"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func LookupDnsSettingsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupDnsSettingsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (LookupDnsSettingsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("netbird:index/getDnsSettings:getDnsSettings", nil, LookupDnsSettingsResultOutput{}, options).(LookupDnsSettingsResultOutput), nil
	}).(LookupDnsSettingsResultOutput)
}

// A collection of values returned by getDnsSettings.
type LookupDnsSettingsResultOutput struct{ *pulumi.OutputState }

func (LookupDnsSettingsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDnsSettingsResult)(nil)).Elem()
}

func (o LookupDnsSettingsResultOutput) ToLookupDnsSettingsResultOutput() LookupDnsSettingsResultOutput {
	return o
}

func (o LookupDnsSettingsResultOutput) ToLookupDnsSettingsResultOutputWithContext(ctx context.Context) LookupDnsSettingsResultOutput {
	return o
}

func (o LookupDnsSettingsResultOutput) DisabledManagementGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDnsSettingsResult) []string { return v.DisabledManagementGroups }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDnsSettingsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDnsSettingsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDnsSettingsResultOutput{})
}
