// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"github.com/KitStream/netbird-pulumi-provider/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPeers(ctx *pulumi.Context, args *GetPeersArgs, opts ...pulumi.InvokeOption) (*GetPeersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPeersResult
	err := ctx.Invoke("netbird:index/getPeers:getPeers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPeers.
type GetPeersArgs struct {
	ApprovalRequired            *bool    `pulumi:"approvalRequired"`
	CityName                    *string  `pulumi:"cityName"`
	Connected                   *bool    `pulumi:"connected"`
	ConnectionIp                *string  `pulumi:"connectionIp"`
	CountryCode                 *string  `pulumi:"countryCode"`
	DnsLabel                    *string  `pulumi:"dnsLabel"`
	ExtraDnsLabels              []string `pulumi:"extraDnsLabels"`
	GeonameId                   *int     `pulumi:"geonameId"`
	Groups                      []string `pulumi:"groups"`
	Hostname                    *string  `pulumi:"hostname"`
	InactivityExpirationEnabled *bool    `pulumi:"inactivityExpirationEnabled"`
	Ip                          *string  `pulumi:"ip"`
	LoginExpirationEnabled      *bool    `pulumi:"loginExpirationEnabled"`
	LoginExpired                *bool    `pulumi:"loginExpired"`
	Name                        *string  `pulumi:"name"`
	Os                          *string  `pulumi:"os"`
	SshEnabled                  *bool    `pulumi:"sshEnabled"`
	UserId                      *string  `pulumi:"userId"`
}

// A collection of values returned by getPeers.
type GetPeersResult struct {
	ApprovalRequired bool     `pulumi:"approvalRequired"`
	CityName         string   `pulumi:"cityName"`
	Connected        bool     `pulumi:"connected"`
	ConnectionIp     string   `pulumi:"connectionIp"`
	CountryCode      string   `pulumi:"countryCode"`
	DnsLabel         string   `pulumi:"dnsLabel"`
	ExtraDnsLabels   []string `pulumi:"extraDnsLabels"`
	GeonameId        int      `pulumi:"geonameId"`
	Groups           []string `pulumi:"groups"`
	Hostname         string   `pulumi:"hostname"`
	// The provider-assigned unique ID for this managed resource.
	Id                          string   `pulumi:"id"`
	Ids                         []string `pulumi:"ids"`
	InactivityExpirationEnabled bool     `pulumi:"inactivityExpirationEnabled"`
	Ip                          string   `pulumi:"ip"`
	KernelVersion               string   `pulumi:"kernelVersion"`
	LastLogin                   string   `pulumi:"lastLogin"`
	LastSeen                    string   `pulumi:"lastSeen"`
	LoginExpirationEnabled      bool     `pulumi:"loginExpirationEnabled"`
	LoginExpired                bool     `pulumi:"loginExpired"`
	Name                        string   `pulumi:"name"`
	Os                          string   `pulumi:"os"`
	SerialNumber                string   `pulumi:"serialNumber"`
	SshEnabled                  bool     `pulumi:"sshEnabled"`
	UiVersion                   string   `pulumi:"uiVersion"`
	UserId                      string   `pulumi:"userId"`
	Version                     string   `pulumi:"version"`
}

func GetPeersOutput(ctx *pulumi.Context, args GetPeersOutputArgs, opts ...pulumi.InvokeOption) GetPeersResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPeersResultOutput, error) {
			args := v.(GetPeersArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:index/getPeers:getPeers", args, GetPeersResultOutput{}, options).(GetPeersResultOutput), nil
		}).(GetPeersResultOutput)
}

// A collection of arguments for invoking getPeers.
type GetPeersOutputArgs struct {
	ApprovalRequired            pulumi.BoolPtrInput     `pulumi:"approvalRequired"`
	CityName                    pulumi.StringPtrInput   `pulumi:"cityName"`
	Connected                   pulumi.BoolPtrInput     `pulumi:"connected"`
	ConnectionIp                pulumi.StringPtrInput   `pulumi:"connectionIp"`
	CountryCode                 pulumi.StringPtrInput   `pulumi:"countryCode"`
	DnsLabel                    pulumi.StringPtrInput   `pulumi:"dnsLabel"`
	ExtraDnsLabels              pulumi.StringArrayInput `pulumi:"extraDnsLabels"`
	GeonameId                   pulumi.IntPtrInput      `pulumi:"geonameId"`
	Groups                      pulumi.StringArrayInput `pulumi:"groups"`
	Hostname                    pulumi.StringPtrInput   `pulumi:"hostname"`
	InactivityExpirationEnabled pulumi.BoolPtrInput     `pulumi:"inactivityExpirationEnabled"`
	Ip                          pulumi.StringPtrInput   `pulumi:"ip"`
	LoginExpirationEnabled      pulumi.BoolPtrInput     `pulumi:"loginExpirationEnabled"`
	LoginExpired                pulumi.BoolPtrInput     `pulumi:"loginExpired"`
	Name                        pulumi.StringPtrInput   `pulumi:"name"`
	Os                          pulumi.StringPtrInput   `pulumi:"os"`
	SshEnabled                  pulumi.BoolPtrInput     `pulumi:"sshEnabled"`
	UserId                      pulumi.StringPtrInput   `pulumi:"userId"`
}

func (GetPeersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPeersArgs)(nil)).Elem()
}

// A collection of values returned by getPeers.
type GetPeersResultOutput struct{ *pulumi.OutputState }

func (GetPeersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPeersResult)(nil)).Elem()
}

func (o GetPeersResultOutput) ToGetPeersResultOutput() GetPeersResultOutput {
	return o
}

func (o GetPeersResultOutput) ToGetPeersResultOutputWithContext(ctx context.Context) GetPeersResultOutput {
	return o
}

func (o GetPeersResultOutput) ApprovalRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.ApprovalRequired }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) CityName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.CityName }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) Connected() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.Connected }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) ConnectionIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.ConnectionIp }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.CountryCode }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) DnsLabel() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.DnsLabel }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) ExtraDnsLabels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPeersResult) []string { return v.ExtraDnsLabels }).(pulumi.StringArrayOutput)
}

func (o GetPeersResultOutput) GeonameId() pulumi.IntOutput {
	return o.ApplyT(func(v GetPeersResult) int { return v.GeonameId }).(pulumi.IntOutput)
}

func (o GetPeersResultOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPeersResult) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

func (o GetPeersResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Hostname }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPeersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPeersResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func (o GetPeersResultOutput) InactivityExpirationEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.InactivityExpirationEnabled }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) KernelVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.KernelVersion }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) LastLogin() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.LastLogin }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.LastSeen }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) LoginExpirationEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.LoginExpirationEnabled }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) LoginExpired() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.LoginExpired }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) Os() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Os }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) SerialNumber() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.SerialNumber }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) SshEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPeersResult) bool { return v.SshEnabled }).(pulumi.BoolOutput)
}

func (o GetPeersResultOutput) UiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.UiVersion }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.UserId }).(pulumi.StringOutput)
}

func (o GetPeersResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetPeersResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPeersResultOutput{})
}
