// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"errors"
	"github.com/KitStream/pulumi-netbird/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkRouter struct {
	pulumi.CustomResourceState

	// Network router status
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade pulumi.BoolOutput `pulumi:"masquerade"`
	// Route metric number. Lowest number has higher priority
	Metric pulumi.IntOutput `pulumi:"metric"`
	// The unique identifier of a network
	NetworkId pulumi.StringOutput `pulumi:"networkId"`
	// Peer Identifier associated with route. This property can not be set together with peer_groups
	Peer pulumi.StringPtrOutput `pulumi:"peer"`
	// Peers Group Identifier associated with route. This property can not be set together with peer
	PeerGroups pulumi.StringArrayOutput `pulumi:"peerGroups"`
}

// NewNetworkRouter registers a new resource with the given unique name, arguments, and options.
func NewNetworkRouter(ctx *pulumi.Context,
	name string, args *NetworkRouterArgs, opts ...pulumi.ResourceOption) (*NetworkRouter, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NetworkId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetworkRouter
	err := ctx.RegisterResource("netbird:index/networkRouter:NetworkRouter", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkRouter gets an existing NetworkRouter resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkRouter(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkRouterState, opts ...pulumi.ResourceOption) (*NetworkRouter, error) {
	var resource NetworkRouter
	err := ctx.ReadResource("netbird:index/networkRouter:NetworkRouter", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkRouter resources.
type networkRouterState struct {
	// Network router status
	Enabled *bool `pulumi:"enabled"`
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade *bool `pulumi:"masquerade"`
	// Route metric number. Lowest number has higher priority
	Metric *int `pulumi:"metric"`
	// The unique identifier of a network
	NetworkId *string `pulumi:"networkId"`
	// Peer Identifier associated with route. This property can not be set together with peer_groups
	Peer *string `pulumi:"peer"`
	// Peers Group Identifier associated with route. This property can not be set together with peer
	PeerGroups []string `pulumi:"peerGroups"`
}

type NetworkRouterState struct {
	// Network router status
	Enabled pulumi.BoolPtrInput
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade pulumi.BoolPtrInput
	// Route metric number. Lowest number has higher priority
	Metric pulumi.IntPtrInput
	// The unique identifier of a network
	NetworkId pulumi.StringPtrInput
	// Peer Identifier associated with route. This property can not be set together with peer_groups
	Peer pulumi.StringPtrInput
	// Peers Group Identifier associated with route. This property can not be set together with peer
	PeerGroups pulumi.StringArrayInput
}

func (NetworkRouterState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkRouterState)(nil)).Elem()
}

type networkRouterArgs struct {
	// Network router status
	Enabled *bool `pulumi:"enabled"`
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade *bool `pulumi:"masquerade"`
	// Route metric number. Lowest number has higher priority
	Metric *int `pulumi:"metric"`
	// The unique identifier of a network
	NetworkId string `pulumi:"networkId"`
	// Peer Identifier associated with route. This property can not be set together with peer_groups
	Peer *string `pulumi:"peer"`
	// Peers Group Identifier associated with route. This property can not be set together with peer
	PeerGroups []string `pulumi:"peerGroups"`
}

// The set of arguments for constructing a NetworkRouter resource.
type NetworkRouterArgs struct {
	// Network router status
	Enabled pulumi.BoolPtrInput
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade pulumi.BoolPtrInput
	// Route metric number. Lowest number has higher priority
	Metric pulumi.IntPtrInput
	// The unique identifier of a network
	NetworkId pulumi.StringInput
	// Peer Identifier associated with route. This property can not be set together with peer_groups
	Peer pulumi.StringPtrInput
	// Peers Group Identifier associated with route. This property can not be set together with peer
	PeerGroups pulumi.StringArrayInput
}

func (NetworkRouterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkRouterArgs)(nil)).Elem()
}

type NetworkRouterInput interface {
	pulumi.Input

	ToNetworkRouterOutput() NetworkRouterOutput
	ToNetworkRouterOutputWithContext(ctx context.Context) NetworkRouterOutput
}

func (*NetworkRouter) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkRouter)(nil)).Elem()
}

func (i *NetworkRouter) ToNetworkRouterOutput() NetworkRouterOutput {
	return i.ToNetworkRouterOutputWithContext(context.Background())
}

func (i *NetworkRouter) ToNetworkRouterOutputWithContext(ctx context.Context) NetworkRouterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkRouterOutput)
}

// NetworkRouterArrayInput is an input type that accepts NetworkRouterArray and NetworkRouterArrayOutput values.
// You can construct a concrete instance of `NetworkRouterArrayInput` via:
//
//	NetworkRouterArray{ NetworkRouterArgs{...} }
type NetworkRouterArrayInput interface {
	pulumi.Input

	ToNetworkRouterArrayOutput() NetworkRouterArrayOutput
	ToNetworkRouterArrayOutputWithContext(context.Context) NetworkRouterArrayOutput
}

type NetworkRouterArray []NetworkRouterInput

func (NetworkRouterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkRouter)(nil)).Elem()
}

func (i NetworkRouterArray) ToNetworkRouterArrayOutput() NetworkRouterArrayOutput {
	return i.ToNetworkRouterArrayOutputWithContext(context.Background())
}

func (i NetworkRouterArray) ToNetworkRouterArrayOutputWithContext(ctx context.Context) NetworkRouterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkRouterArrayOutput)
}

// NetworkRouterMapInput is an input type that accepts NetworkRouterMap and NetworkRouterMapOutput values.
// You can construct a concrete instance of `NetworkRouterMapInput` via:
//
//	NetworkRouterMap{ "key": NetworkRouterArgs{...} }
type NetworkRouterMapInput interface {
	pulumi.Input

	ToNetworkRouterMapOutput() NetworkRouterMapOutput
	ToNetworkRouterMapOutputWithContext(context.Context) NetworkRouterMapOutput
}

type NetworkRouterMap map[string]NetworkRouterInput

func (NetworkRouterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkRouter)(nil)).Elem()
}

func (i NetworkRouterMap) ToNetworkRouterMapOutput() NetworkRouterMapOutput {
	return i.ToNetworkRouterMapOutputWithContext(context.Background())
}

func (i NetworkRouterMap) ToNetworkRouterMapOutputWithContext(ctx context.Context) NetworkRouterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkRouterMapOutput)
}

type NetworkRouterOutput struct{ *pulumi.OutputState }

func (NetworkRouterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkRouter)(nil)).Elem()
}

func (o NetworkRouterOutput) ToNetworkRouterOutput() NetworkRouterOutput {
	return o
}

func (o NetworkRouterOutput) ToNetworkRouterOutputWithContext(ctx context.Context) NetworkRouterOutput {
	return o
}

// Network router status
func (o NetworkRouterOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Indicate if peer should masquerade traffic to this route's prefix
func (o NetworkRouterOutput) Masquerade() pulumi.BoolOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.BoolOutput { return v.Masquerade }).(pulumi.BoolOutput)
}

// Route metric number. Lowest number has higher priority
func (o NetworkRouterOutput) Metric() pulumi.IntOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.IntOutput { return v.Metric }).(pulumi.IntOutput)
}

// The unique identifier of a network
func (o NetworkRouterOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

// Peer Identifier associated with route. This property can not be set together with peer_groups
func (o NetworkRouterOutput) Peer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.StringPtrOutput { return v.Peer }).(pulumi.StringPtrOutput)
}

// Peers Group Identifier associated with route. This property can not be set together with peer
func (o NetworkRouterOutput) PeerGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetworkRouter) pulumi.StringArrayOutput { return v.PeerGroups }).(pulumi.StringArrayOutput)
}

type NetworkRouterArrayOutput struct{ *pulumi.OutputState }

func (NetworkRouterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkRouter)(nil)).Elem()
}

func (o NetworkRouterArrayOutput) ToNetworkRouterArrayOutput() NetworkRouterArrayOutput {
	return o
}

func (o NetworkRouterArrayOutput) ToNetworkRouterArrayOutputWithContext(ctx context.Context) NetworkRouterArrayOutput {
	return o
}

func (o NetworkRouterArrayOutput) Index(i pulumi.IntInput) NetworkRouterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NetworkRouter {
		return vs[0].([]*NetworkRouter)[vs[1].(int)]
	}).(NetworkRouterOutput)
}

type NetworkRouterMapOutput struct{ *pulumi.OutputState }

func (NetworkRouterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkRouter)(nil)).Elem()
}

func (o NetworkRouterMapOutput) ToNetworkRouterMapOutput() NetworkRouterMapOutput {
	return o
}

func (o NetworkRouterMapOutput) ToNetworkRouterMapOutputWithContext(ctx context.Context) NetworkRouterMapOutput {
	return o
}

func (o NetworkRouterMapOutput) MapIndex(k pulumi.StringInput) NetworkRouterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NetworkRouter {
		return vs[0].(map[string]*NetworkRouter)[vs[1].(string)]
	}).(NetworkRouterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkRouterInput)(nil)).Elem(), &NetworkRouter{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkRouterArrayInput)(nil)).Elem(), NetworkRouterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkRouterMapInput)(nil)).Elem(), NetworkRouterMap{})
	pulumi.RegisterOutputType(NetworkRouterOutput{})
	pulumi.RegisterOutputType(NetworkRouterArrayOutput{})
	pulumi.RegisterOutputType(NetworkRouterMapOutput{})
}
