// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"errors"
	"github.com/KitStream/pulumi-netbird/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PostureCheck struct {
	pulumi.CustomResourceState

	// PostureCheck description
	Description      pulumi.StringPtrOutput                `pulumi:"description"`
	GeoLocationCheck PostureCheckGeoLocationCheckPtrOutput `pulumi:"geoLocationCheck"`
	// PostureCheck Name
	Name                  pulumi.StringOutput                        `pulumi:"name"`
	NetbirdVersionCheck   PostureCheckNetbirdVersionCheckPtrOutput   `pulumi:"netbirdVersionCheck"`
	OsVersionCheck        PostureCheckOsVersionCheckPtrOutput        `pulumi:"osVersionCheck"`
	PeerNetworkRangeCheck PostureCheckPeerNetworkRangeCheckPtrOutput `pulumi:"peerNetworkRangeCheck"`
	ProcessChecks         PostureCheckProcessCheckArrayOutput        `pulumi:"processChecks"`
}

// NewPostureCheck registers a new resource with the given unique name, arguments, and options.
func NewPostureCheck(ctx *pulumi.Context,
	name string, args *PostureCheckArgs, opts ...pulumi.ResourceOption) (*PostureCheck, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PostureCheck
	err := ctx.RegisterResource("netbird:index/postureCheck:PostureCheck", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostureCheck gets an existing PostureCheck resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostureCheck(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostureCheckState, opts ...pulumi.ResourceOption) (*PostureCheck, error) {
	var resource PostureCheck
	err := ctx.ReadResource("netbird:index/postureCheck:PostureCheck", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PostureCheck resources.
type postureCheckState struct {
	// PostureCheck description
	Description      *string                       `pulumi:"description"`
	GeoLocationCheck *PostureCheckGeoLocationCheck `pulumi:"geoLocationCheck"`
	// PostureCheck Name
	Name                  *string                            `pulumi:"name"`
	NetbirdVersionCheck   *PostureCheckNetbirdVersionCheck   `pulumi:"netbirdVersionCheck"`
	OsVersionCheck        *PostureCheckOsVersionCheck        `pulumi:"osVersionCheck"`
	PeerNetworkRangeCheck *PostureCheckPeerNetworkRangeCheck `pulumi:"peerNetworkRangeCheck"`
	ProcessChecks         []PostureCheckProcessCheck         `pulumi:"processChecks"`
}

type PostureCheckState struct {
	// PostureCheck description
	Description      pulumi.StringPtrInput
	GeoLocationCheck PostureCheckGeoLocationCheckPtrInput
	// PostureCheck Name
	Name                  pulumi.StringPtrInput
	NetbirdVersionCheck   PostureCheckNetbirdVersionCheckPtrInput
	OsVersionCheck        PostureCheckOsVersionCheckPtrInput
	PeerNetworkRangeCheck PostureCheckPeerNetworkRangeCheckPtrInput
	ProcessChecks         PostureCheckProcessCheckArrayInput
}

func (PostureCheckState) ElementType() reflect.Type {
	return reflect.TypeOf((*postureCheckState)(nil)).Elem()
}

type postureCheckArgs struct {
	// PostureCheck description
	Description      *string                       `pulumi:"description"`
	GeoLocationCheck *PostureCheckGeoLocationCheck `pulumi:"geoLocationCheck"`
	// PostureCheck Name
	Name                  string                             `pulumi:"name"`
	NetbirdVersionCheck   *PostureCheckNetbirdVersionCheck   `pulumi:"netbirdVersionCheck"`
	OsVersionCheck        *PostureCheckOsVersionCheck        `pulumi:"osVersionCheck"`
	PeerNetworkRangeCheck *PostureCheckPeerNetworkRangeCheck `pulumi:"peerNetworkRangeCheck"`
	ProcessChecks         []PostureCheckProcessCheck         `pulumi:"processChecks"`
}

// The set of arguments for constructing a PostureCheck resource.
type PostureCheckArgs struct {
	// PostureCheck description
	Description      pulumi.StringPtrInput
	GeoLocationCheck PostureCheckGeoLocationCheckPtrInput
	// PostureCheck Name
	Name                  pulumi.StringInput
	NetbirdVersionCheck   PostureCheckNetbirdVersionCheckPtrInput
	OsVersionCheck        PostureCheckOsVersionCheckPtrInput
	PeerNetworkRangeCheck PostureCheckPeerNetworkRangeCheckPtrInput
	ProcessChecks         PostureCheckProcessCheckArrayInput
}

func (PostureCheckArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postureCheckArgs)(nil)).Elem()
}

type PostureCheckInput interface {
	pulumi.Input

	ToPostureCheckOutput() PostureCheckOutput
	ToPostureCheckOutputWithContext(ctx context.Context) PostureCheckOutput
}

func (*PostureCheck) ElementType() reflect.Type {
	return reflect.TypeOf((**PostureCheck)(nil)).Elem()
}

func (i *PostureCheck) ToPostureCheckOutput() PostureCheckOutput {
	return i.ToPostureCheckOutputWithContext(context.Background())
}

func (i *PostureCheck) ToPostureCheckOutputWithContext(ctx context.Context) PostureCheckOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostureCheckOutput)
}

// PostureCheckArrayInput is an input type that accepts PostureCheckArray and PostureCheckArrayOutput values.
// You can construct a concrete instance of `PostureCheckArrayInput` via:
//
//	PostureCheckArray{ PostureCheckArgs{...} }
type PostureCheckArrayInput interface {
	pulumi.Input

	ToPostureCheckArrayOutput() PostureCheckArrayOutput
	ToPostureCheckArrayOutputWithContext(context.Context) PostureCheckArrayOutput
}

type PostureCheckArray []PostureCheckInput

func (PostureCheckArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PostureCheck)(nil)).Elem()
}

func (i PostureCheckArray) ToPostureCheckArrayOutput() PostureCheckArrayOutput {
	return i.ToPostureCheckArrayOutputWithContext(context.Background())
}

func (i PostureCheckArray) ToPostureCheckArrayOutputWithContext(ctx context.Context) PostureCheckArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostureCheckArrayOutput)
}

// PostureCheckMapInput is an input type that accepts PostureCheckMap and PostureCheckMapOutput values.
// You can construct a concrete instance of `PostureCheckMapInput` via:
//
//	PostureCheckMap{ "key": PostureCheckArgs{...} }
type PostureCheckMapInput interface {
	pulumi.Input

	ToPostureCheckMapOutput() PostureCheckMapOutput
	ToPostureCheckMapOutputWithContext(context.Context) PostureCheckMapOutput
}

type PostureCheckMap map[string]PostureCheckInput

func (PostureCheckMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PostureCheck)(nil)).Elem()
}

func (i PostureCheckMap) ToPostureCheckMapOutput() PostureCheckMapOutput {
	return i.ToPostureCheckMapOutputWithContext(context.Background())
}

func (i PostureCheckMap) ToPostureCheckMapOutputWithContext(ctx context.Context) PostureCheckMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostureCheckMapOutput)
}

type PostureCheckOutput struct{ *pulumi.OutputState }

func (PostureCheckOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostureCheck)(nil)).Elem()
}

func (o PostureCheckOutput) ToPostureCheckOutput() PostureCheckOutput {
	return o
}

func (o PostureCheckOutput) ToPostureCheckOutputWithContext(ctx context.Context) PostureCheckOutput {
	return o
}

// PostureCheck description
func (o PostureCheckOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostureCheck) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o PostureCheckOutput) GeoLocationCheck() PostureCheckGeoLocationCheckPtrOutput {
	return o.ApplyT(func(v *PostureCheck) PostureCheckGeoLocationCheckPtrOutput { return v.GeoLocationCheck }).(PostureCheckGeoLocationCheckPtrOutput)
}

// PostureCheck Name
func (o PostureCheckOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PostureCheck) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PostureCheckOutput) NetbirdVersionCheck() PostureCheckNetbirdVersionCheckPtrOutput {
	return o.ApplyT(func(v *PostureCheck) PostureCheckNetbirdVersionCheckPtrOutput { return v.NetbirdVersionCheck }).(PostureCheckNetbirdVersionCheckPtrOutput)
}

func (o PostureCheckOutput) OsVersionCheck() PostureCheckOsVersionCheckPtrOutput {
	return o.ApplyT(func(v *PostureCheck) PostureCheckOsVersionCheckPtrOutput { return v.OsVersionCheck }).(PostureCheckOsVersionCheckPtrOutput)
}

func (o PostureCheckOutput) PeerNetworkRangeCheck() PostureCheckPeerNetworkRangeCheckPtrOutput {
	return o.ApplyT(func(v *PostureCheck) PostureCheckPeerNetworkRangeCheckPtrOutput { return v.PeerNetworkRangeCheck }).(PostureCheckPeerNetworkRangeCheckPtrOutput)
}

func (o PostureCheckOutput) ProcessChecks() PostureCheckProcessCheckArrayOutput {
	return o.ApplyT(func(v *PostureCheck) PostureCheckProcessCheckArrayOutput { return v.ProcessChecks }).(PostureCheckProcessCheckArrayOutput)
}

type PostureCheckArrayOutput struct{ *pulumi.OutputState }

func (PostureCheckArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PostureCheck)(nil)).Elem()
}

func (o PostureCheckArrayOutput) ToPostureCheckArrayOutput() PostureCheckArrayOutput {
	return o
}

func (o PostureCheckArrayOutput) ToPostureCheckArrayOutputWithContext(ctx context.Context) PostureCheckArrayOutput {
	return o
}

func (o PostureCheckArrayOutput) Index(i pulumi.IntInput) PostureCheckOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PostureCheck {
		return vs[0].([]*PostureCheck)[vs[1].(int)]
	}).(PostureCheckOutput)
}

type PostureCheckMapOutput struct{ *pulumi.OutputState }

func (PostureCheckMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PostureCheck)(nil)).Elem()
}

func (o PostureCheckMapOutput) ToPostureCheckMapOutput() PostureCheckMapOutput {
	return o
}

func (o PostureCheckMapOutput) ToPostureCheckMapOutputWithContext(ctx context.Context) PostureCheckMapOutput {
	return o
}

func (o PostureCheckMapOutput) MapIndex(k pulumi.StringInput) PostureCheckOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PostureCheck {
		return vs[0].(map[string]*PostureCheck)[vs[1].(string)]
	}).(PostureCheckOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostureCheckInput)(nil)).Elem(), &PostureCheck{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostureCheckArrayInput)(nil)).Elem(), PostureCheckArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostureCheckMapInput)(nil)).Elem(), PostureCheckMap{})
	pulumi.RegisterOutputType(PostureCheckOutput{})
	pulumi.RegisterOutputType(PostureCheckArrayOutput{})
	pulumi.RegisterOutputType(PostureCheckMapOutput{})
}
