# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetAccountSettingsResult',
    'AwaitableGetAccountSettingsResult',
    'get_account_settings',
    'get_account_settings_output',
]

@pulumi.output_type
class GetAccountSettingsResult:
    """
    A collection of values returned by getAccountSettings.
    """
    def __init__(__self__, groups_propagation_enabled=None, id=None, jwt_allow_groups=None, jwt_groups_claim_name=None, jwt_groups_enabled=None, network_traffic_logs_enabled=None, network_traffic_packet_counter_enabled=None, peer_approval_enabled=None, peer_inactivity_expiration=None, peer_inactivity_expiration_enabled=None, peer_login_expiration=None, peer_login_expiration_enabled=None, regular_users_view_blocked=None, routing_peer_dns_resolution_enabled=None):
        if groups_propagation_enabled and not isinstance(groups_propagation_enabled, bool):
            raise TypeError("Expected argument 'groups_propagation_enabled' to be a bool")
        pulumi.set(__self__, "groups_propagation_enabled", groups_propagation_enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if jwt_allow_groups and not isinstance(jwt_allow_groups, list):
            raise TypeError("Expected argument 'jwt_allow_groups' to be a list")
        pulumi.set(__self__, "jwt_allow_groups", jwt_allow_groups)
        if jwt_groups_claim_name and not isinstance(jwt_groups_claim_name, str):
            raise TypeError("Expected argument 'jwt_groups_claim_name' to be a str")
        pulumi.set(__self__, "jwt_groups_claim_name", jwt_groups_claim_name)
        if jwt_groups_enabled and not isinstance(jwt_groups_enabled, bool):
            raise TypeError("Expected argument 'jwt_groups_enabled' to be a bool")
        pulumi.set(__self__, "jwt_groups_enabled", jwt_groups_enabled)
        if network_traffic_logs_enabled and not isinstance(network_traffic_logs_enabled, bool):
            raise TypeError("Expected argument 'network_traffic_logs_enabled' to be a bool")
        pulumi.set(__self__, "network_traffic_logs_enabled", network_traffic_logs_enabled)
        if network_traffic_packet_counter_enabled and not isinstance(network_traffic_packet_counter_enabled, bool):
            raise TypeError("Expected argument 'network_traffic_packet_counter_enabled' to be a bool")
        pulumi.set(__self__, "network_traffic_packet_counter_enabled", network_traffic_packet_counter_enabled)
        if peer_approval_enabled and not isinstance(peer_approval_enabled, bool):
            raise TypeError("Expected argument 'peer_approval_enabled' to be a bool")
        pulumi.set(__self__, "peer_approval_enabled", peer_approval_enabled)
        if peer_inactivity_expiration and not isinstance(peer_inactivity_expiration, int):
            raise TypeError("Expected argument 'peer_inactivity_expiration' to be a int")
        pulumi.set(__self__, "peer_inactivity_expiration", peer_inactivity_expiration)
        if peer_inactivity_expiration_enabled and not isinstance(peer_inactivity_expiration_enabled, bool):
            raise TypeError("Expected argument 'peer_inactivity_expiration_enabled' to be a bool")
        pulumi.set(__self__, "peer_inactivity_expiration_enabled", peer_inactivity_expiration_enabled)
        if peer_login_expiration and not isinstance(peer_login_expiration, int):
            raise TypeError("Expected argument 'peer_login_expiration' to be a int")
        pulumi.set(__self__, "peer_login_expiration", peer_login_expiration)
        if peer_login_expiration_enabled and not isinstance(peer_login_expiration_enabled, bool):
            raise TypeError("Expected argument 'peer_login_expiration_enabled' to be a bool")
        pulumi.set(__self__, "peer_login_expiration_enabled", peer_login_expiration_enabled)
        if regular_users_view_blocked and not isinstance(regular_users_view_blocked, bool):
            raise TypeError("Expected argument 'regular_users_view_blocked' to be a bool")
        pulumi.set(__self__, "regular_users_view_blocked", regular_users_view_blocked)
        if routing_peer_dns_resolution_enabled and not isinstance(routing_peer_dns_resolution_enabled, bool):
            raise TypeError("Expected argument 'routing_peer_dns_resolution_enabled' to be a bool")
        pulumi.set(__self__, "routing_peer_dns_resolution_enabled", routing_peer_dns_resolution_enabled)

    @_builtins.property
    @pulumi.getter(name="groupsPropagationEnabled")
    def groups_propagation_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "groups_propagation_enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="jwtAllowGroups")
    def jwt_allow_groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "jwt_allow_groups")

    @_builtins.property
    @pulumi.getter(name="jwtGroupsClaimName")
    def jwt_groups_claim_name(self) -> _builtins.str:
        return pulumi.get(self, "jwt_groups_claim_name")

    @_builtins.property
    @pulumi.getter(name="jwtGroupsEnabled")
    def jwt_groups_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "jwt_groups_enabled")

    @_builtins.property
    @pulumi.getter(name="networkTrafficLogsEnabled")
    def network_traffic_logs_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "network_traffic_logs_enabled")

    @_builtins.property
    @pulumi.getter(name="networkTrafficPacketCounterEnabled")
    def network_traffic_packet_counter_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "network_traffic_packet_counter_enabled")

    @_builtins.property
    @pulumi.getter(name="peerApprovalEnabled")
    def peer_approval_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "peer_approval_enabled")

    @_builtins.property
    @pulumi.getter(name="peerInactivityExpiration")
    def peer_inactivity_expiration(self) -> _builtins.int:
        return pulumi.get(self, "peer_inactivity_expiration")

    @_builtins.property
    @pulumi.getter(name="peerInactivityExpirationEnabled")
    def peer_inactivity_expiration_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "peer_inactivity_expiration_enabled")

    @_builtins.property
    @pulumi.getter(name="peerLoginExpiration")
    def peer_login_expiration(self) -> _builtins.int:
        return pulumi.get(self, "peer_login_expiration")

    @_builtins.property
    @pulumi.getter(name="peerLoginExpirationEnabled")
    def peer_login_expiration_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "peer_login_expiration_enabled")

    @_builtins.property
    @pulumi.getter(name="regularUsersViewBlocked")
    def regular_users_view_blocked(self) -> _builtins.bool:
        return pulumi.get(self, "regular_users_view_blocked")

    @_builtins.property
    @pulumi.getter(name="routingPeerDnsResolutionEnabled")
    def routing_peer_dns_resolution_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "routing_peer_dns_resolution_enabled")


class AwaitableGetAccountSettingsResult(GetAccountSettingsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAccountSettingsResult(
            groups_propagation_enabled=self.groups_propagation_enabled,
            id=self.id,
            jwt_allow_groups=self.jwt_allow_groups,
            jwt_groups_claim_name=self.jwt_groups_claim_name,
            jwt_groups_enabled=self.jwt_groups_enabled,
            network_traffic_logs_enabled=self.network_traffic_logs_enabled,
            network_traffic_packet_counter_enabled=self.network_traffic_packet_counter_enabled,
            peer_approval_enabled=self.peer_approval_enabled,
            peer_inactivity_expiration=self.peer_inactivity_expiration,
            peer_inactivity_expiration_enabled=self.peer_inactivity_expiration_enabled,
            peer_login_expiration=self.peer_login_expiration,
            peer_login_expiration_enabled=self.peer_login_expiration_enabled,
            regular_users_view_blocked=self.regular_users_view_blocked,
            routing_peer_dns_resolution_enabled=self.routing_peer_dns_resolution_enabled)


def get_account_settings(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAccountSettingsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getAccountSettings:getAccountSettings', __args__, opts=opts, typ=GetAccountSettingsResult).value

    return AwaitableGetAccountSettingsResult(
        groups_propagation_enabled=pulumi.get(__ret__, 'groups_propagation_enabled'),
        id=pulumi.get(__ret__, 'id'),
        jwt_allow_groups=pulumi.get(__ret__, 'jwt_allow_groups'),
        jwt_groups_claim_name=pulumi.get(__ret__, 'jwt_groups_claim_name'),
        jwt_groups_enabled=pulumi.get(__ret__, 'jwt_groups_enabled'),
        network_traffic_logs_enabled=pulumi.get(__ret__, 'network_traffic_logs_enabled'),
        network_traffic_packet_counter_enabled=pulumi.get(__ret__, 'network_traffic_packet_counter_enabled'),
        peer_approval_enabled=pulumi.get(__ret__, 'peer_approval_enabled'),
        peer_inactivity_expiration=pulumi.get(__ret__, 'peer_inactivity_expiration'),
        peer_inactivity_expiration_enabled=pulumi.get(__ret__, 'peer_inactivity_expiration_enabled'),
        peer_login_expiration=pulumi.get(__ret__, 'peer_login_expiration'),
        peer_login_expiration_enabled=pulumi.get(__ret__, 'peer_login_expiration_enabled'),
        regular_users_view_blocked=pulumi.get(__ret__, 'regular_users_view_blocked'),
        routing_peer_dns_resolution_enabled=pulumi.get(__ret__, 'routing_peer_dns_resolution_enabled'))
def get_account_settings_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAccountSettingsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getAccountSettings:getAccountSettings', __args__, opts=opts, typ=GetAccountSettingsResult)
    return __ret__.apply(lambda __response__: GetAccountSettingsResult(
        groups_propagation_enabled=pulumi.get(__response__, 'groups_propagation_enabled'),
        id=pulumi.get(__response__, 'id'),
        jwt_allow_groups=pulumi.get(__response__, 'jwt_allow_groups'),
        jwt_groups_claim_name=pulumi.get(__response__, 'jwt_groups_claim_name'),
        jwt_groups_enabled=pulumi.get(__response__, 'jwt_groups_enabled'),
        network_traffic_logs_enabled=pulumi.get(__response__, 'network_traffic_logs_enabled'),
        network_traffic_packet_counter_enabled=pulumi.get(__response__, 'network_traffic_packet_counter_enabled'),
        peer_approval_enabled=pulumi.get(__response__, 'peer_approval_enabled'),
        peer_inactivity_expiration=pulumi.get(__response__, 'peer_inactivity_expiration'),
        peer_inactivity_expiration_enabled=pulumi.get(__response__, 'peer_inactivity_expiration_enabled'),
        peer_login_expiration=pulumi.get(__response__, 'peer_login_expiration'),
        peer_login_expiration_enabled=pulumi.get(__response__, 'peer_login_expiration_enabled'),
        regular_users_view_blocked=pulumi.get(__response__, 'regular_users_view_blocked'),
        routing_peer_dns_resolution_enabled=pulumi.get(__response__, 'routing_peer_dns_resolution_enabled')))
