// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PostureCheckGeoLocationCheckLocation
    {
        public readonly string? CityName;
        public readonly string CountryCode;

        [OutputConstructor]
        private PostureCheckGeoLocationCheckLocation(
            string? cityName,

            string countryCode)
        {
            CityName = cityName;
            CountryCode = countryCode;
        }
    }
}
