// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class TokenArgs extends com.pulumi.resources.ResourceArgs {

    public static final TokenArgs Empty = new TokenArgs();

    @Import(name="expirationDays", required=true)
    private Output<Integer> expirationDays;

    public Output<Integer> expirationDays() {
        return this.expirationDays;
    }

    /**
     * Token Name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Token Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * User ID
     * 
     */
    @Import(name="userId", required=true)
    private Output<String> userId;

    /**
     * @return User ID
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    private TokenArgs() {}

    private TokenArgs(TokenArgs $) {
        this.expirationDays = $.expirationDays;
        this.name = $.name;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TokenArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TokenArgs $;

        public Builder() {
            $ = new TokenArgs();
        }

        public Builder(TokenArgs defaults) {
            $ = new TokenArgs(Objects.requireNonNull(defaults));
        }

        public Builder expirationDays(Output<Integer> expirationDays) {
            $.expirationDays = expirationDays;
            return this;
        }

        public Builder expirationDays(Integer expirationDays) {
            return expirationDays(Output.of(expirationDays));
        }

        /**
         * @param name Token Name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Token Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param userId User ID
         * 
         * @return builder
         * 
         */
        public Builder userId(Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId User ID
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public TokenArgs build() {
            if ($.expirationDays == null) {
                throw new MissingRequiredPropertyException("TokenArgs", "expirationDays");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("TokenArgs", "name");
            }
            if ($.userId == null) {
                throw new MissingRequiredPropertyException("TokenArgs", "userId");
            }
            return $;
        }
    }

}
