// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserArgs Empty = new UserArgs();

    /**
     * Group IDs to auto-assign to peers registered by this user
     * 
     */
    @Import(name="autoGroups")
    private @Nullable Output<List<String>> autoGroups;

    /**
     * @return Group IDs to auto-assign to peers registered by this user
     * 
     */
    public Optional<Output<List<String>>> autoGroups() {
        return Optional.ofNullable(this.autoGroups);
    }

    /**
     * User Email
     * 
     */
    @Import(name="email")
    private @Nullable Output<String> email;

    /**
     * @return User Email
     * 
     */
    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * If set to true then user is blocked and can&#39;t use the system
     * 
     */
    @Import(name="isBlocked")
    private @Nullable Output<Boolean> isBlocked;

    /**
     * @return If set to true then user is blocked and can&#39;t use the system
     * 
     */
    public Optional<Output<Boolean>> isBlocked() {
        return Optional.ofNullable(this.isBlocked);
    }

    /**
     * If set to true, creates a Service Account User
     * 
     */
    @Import(name="isServiceUser", required=true)
    private Output<Boolean> isServiceUser;

    /**
     * @return If set to true, creates a Service Account User
     * 
     */
    public Output<Boolean> isServiceUser() {
        return this.isServiceUser;
    }

    /**
     * User Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return User Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     * 
     */
    @Import(name="role")
    private @Nullable Output<String> role;

    /**
     * @return User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     * 
     */
    public Optional<Output<String>> role() {
        return Optional.ofNullable(this.role);
    }

    private UserArgs() {}

    private UserArgs(UserArgs $) {
        this.autoGroups = $.autoGroups;
        this.email = $.email;
        this.isBlocked = $.isBlocked;
        this.isServiceUser = $.isServiceUser;
        this.name = $.name;
        this.role = $.role;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserArgs $;

        public Builder() {
            $ = new UserArgs();
        }

        public Builder(UserArgs defaults) {
            $ = new UserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autoGroups Group IDs to auto-assign to peers registered by this user
         * 
         * @return builder
         * 
         */
        public Builder autoGroups(@Nullable Output<List<String>> autoGroups) {
            $.autoGroups = autoGroups;
            return this;
        }

        /**
         * @param autoGroups Group IDs to auto-assign to peers registered by this user
         * 
         * @return builder
         * 
         */
        public Builder autoGroups(List<String> autoGroups) {
            return autoGroups(Output.of(autoGroups));
        }

        /**
         * @param autoGroups Group IDs to auto-assign to peers registered by this user
         * 
         * @return builder
         * 
         */
        public Builder autoGroups(String... autoGroups) {
            return autoGroups(List.of(autoGroups));
        }

        /**
         * @param email User Email
         * 
         * @return builder
         * 
         */
        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email User Email
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param isBlocked If set to true then user is blocked and can&#39;t use the system
         * 
         * @return builder
         * 
         */
        public Builder isBlocked(@Nullable Output<Boolean> isBlocked) {
            $.isBlocked = isBlocked;
            return this;
        }

        /**
         * @param isBlocked If set to true then user is blocked and can&#39;t use the system
         * 
         * @return builder
         * 
         */
        public Builder isBlocked(Boolean isBlocked) {
            return isBlocked(Output.of(isBlocked));
        }

        /**
         * @param isServiceUser If set to true, creates a Service Account User
         * 
         * @return builder
         * 
         */
        public Builder isServiceUser(Output<Boolean> isServiceUser) {
            $.isServiceUser = isServiceUser;
            return this;
        }

        /**
         * @param isServiceUser If set to true, creates a Service Account User
         * 
         * @return builder
         * 
         */
        public Builder isServiceUser(Boolean isServiceUser) {
            return isServiceUser(Output.of(isServiceUser));
        }

        /**
         * @param name User Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name User Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param role User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
         * 
         * @return builder
         * 
         */
        public Builder role(@Nullable Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        public UserArgs build() {
            if ($.isServiceUser == null) {
                throw new MissingRequiredPropertyException("UserArgs", "isServiceUser");
            }
            return $;
        }
    }

}
