// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.netbird.netbird.UserArgs;
import com.netbird.netbird.Utilities;
import com.netbird.netbird.inputs.UserState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="netbird:index/user:User")
public class User extends com.pulumi.resources.CustomResource {
    /**
     * Group IDs to auto-assign to peers registered by this user
     * 
     */
    @Export(name="autoGroups", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> autoGroups;

    /**
     * @return Group IDs to auto-assign to peers registered by this user
     * 
     */
    public Output<List<String>> autoGroups() {
        return this.autoGroups;
    }
    /**
     * User Email
     * 
     */
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    /**
     * @return User Email
     * 
     */
    public Output<String> email() {
        return this.email;
    }
    /**
     * If set to true then user is blocked and can&#39;t use the system
     * 
     */
    @Export(name="isBlocked", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isBlocked;

    /**
     * @return If set to true then user is blocked and can&#39;t use the system
     * 
     */
    public Output<Boolean> isBlocked() {
        return this.isBlocked;
    }
    /**
     * Set to true if the caller user is the same as the resource user
     * 
     */
    @Export(name="isCurrent", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isCurrent;

    /**
     * @return Set to true if the caller user is the same as the resource user
     * 
     */
    public Output<Boolean> isCurrent() {
        return this.isCurrent;
    }
    /**
     * If set to true, creates a Service Account User
     * 
     */
    @Export(name="isServiceUser", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isServiceUser;

    /**
     * @return If set to true, creates a Service Account User
     * 
     */
    public Output<Boolean> isServiceUser() {
        return this.isServiceUser;
    }
    /**
     * User issue method
     * 
     */
    @Export(name="issued", refs={String.class}, tree="[0]")
    private Output<String> issued;

    /**
     * @return User issue method
     * 
     */
    public Output<String> issued() {
        return this.issued;
    }
    /**
     * User Last Login timedate
     * 
     */
    @Export(name="lastLogin", refs={String.class}, tree="[0]")
    private Output<String> lastLogin;

    /**
     * @return User Last Login timedate
     * 
     */
    public Output<String> lastLogin() {
        return this.lastLogin;
    }
    /**
     * User Name
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return User Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     * 
     */
    @Export(name="role", refs={String.class}, tree="[0]")
    private Output<String> role;

    /**
     * @return User&#39;s NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     * 
     */
    public Output<String> role() {
        return this.role;
    }
    /**
     * User status (active or invited)
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return User status (active or invited)
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public User(java.lang.String name) {
        this(name, UserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public User(java.lang.String name, UserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public User(java.lang.String name, UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/user:User", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private User(java.lang.String name, Output<java.lang.String> id, @Nullable UserState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/user:User", name, state, makeResourceOptions(options, id), false);
    }

    private static UserArgs makeArgs(UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UserArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static User get(java.lang.String name, Output<java.lang.String> id, @Nullable UserState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new User(name, id, state, options);
    }
}
