// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNetworkRouterArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNetworkRouterArgs Empty = new GetNetworkRouterArgs();

    @Import(name="id", required=true)
    private Output<String> id;

    public Output<String> id() {
        return this.id;
    }

    @Import(name="networkId", required=true)
    private Output<String> networkId;

    public Output<String> networkId() {
        return this.networkId;
    }

    private GetNetworkRouterArgs() {}

    private GetNetworkRouterArgs(GetNetworkRouterArgs $) {
        this.id = $.id;
        this.networkId = $.networkId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNetworkRouterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkRouterArgs $;

        public Builder() {
            $ = new GetNetworkRouterArgs();
        }

        public Builder(GetNetworkRouterArgs defaults) {
            $ = new GetNetworkRouterArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder networkId(Output<String> networkId) {
            $.networkId = networkId;
            return this;
        }

        public Builder networkId(String networkId) {
            return networkId(Output.of(networkId));
        }

        public GetNetworkRouterArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetNetworkRouterArgs", "id");
            }
            if ($.networkId == null) {
                throw new MissingRequiredPropertyException("GetNetworkRouterArgs", "networkId");
            }
            return $;
        }
    }

}
