// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetPolicyRuleSourceResourceArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetPolicyRuleSourceResourceArgs Empty = new GetPolicyRuleSourceResourceArgs();

    @Import(name="id", required=true)
    private Output<String> id;

    public Output<String> id() {
        return this.id;
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private GetPolicyRuleSourceResourceArgs() {}

    private GetPolicyRuleSourceResourceArgs(GetPolicyRuleSourceResourceArgs $) {
        this.id = $.id;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPolicyRuleSourceResourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPolicyRuleSourceResourceArgs $;

        public Builder() {
            $ = new GetPolicyRuleSourceResourceArgs();
        }

        public Builder(GetPolicyRuleSourceResourceArgs defaults) {
            $ = new GetPolicyRuleSourceResourceArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public GetPolicyRuleSourceResourceArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleSourceResourceArgs", "id");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleSourceResourceArgs", "type");
            }
            return $;
        }
    }

}
