// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.netbird.netbird.inputs.GetPolicyRuleDestinationResourceArgs;
import com.netbird.netbird.inputs.GetPolicyRulePortRangeArgs;
import com.netbird.netbird.inputs.GetPolicyRuleSourceResourceArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class GetPolicyRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetPolicyRuleArgs Empty = new GetPolicyRuleArgs();

    /**
     * Policy Rule Action (accept|drop)
     * 
     */
    @Import(name="action", required=true)
    private Output<String> action;

    /**
     * @return Policy Rule Action (accept|drop)
     * 
     */
    public Output<String> action() {
        return this.action;
    }

    /**
     * Policy Rule Bidirectional
     * 
     */
    @Import(name="bidirectional", required=true)
    private Output<Boolean> bidirectional;

    /**
     * @return Policy Rule Bidirectional
     * 
     */
    public Output<Boolean> bidirectional() {
        return this.bidirectional;
    }

    /**
     * Policy description
     * 
     */
    @Import(name="description", required=true)
    private Output<String> description;

    /**
     * @return Policy description
     * 
     */
    public Output<String> description() {
        return this.description;
    }

    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     * 
     */
    @Import(name="destinationResource", required=true)
    private Output<GetPolicyRuleDestinationResourceArgs> destinationResource;

    /**
     * @return Policy Rule Destination Resource (mutually exclusive with destinations)
     * 
     */
    public Output<GetPolicyRuleDestinationResourceArgs> destinationResource() {
        return this.destinationResource;
    }

    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     * 
     */
    @Import(name="destinations", required=true)
    private Output<List<String>> destinations;

    /**
     * @return Policy Rule Destination Groups (mutually exclusive with destination_resource)
     * 
     */
    public Output<List<String>> destinations() {
        return this.destinations;
    }

    /**
     * Policy Rule Enabled
     * 
     */
    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    /**
     * @return Policy Rule Enabled
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }

    /**
     * Policy ID
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return Policy ID
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * Policy Name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Policy Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     * 
     */
    @Import(name="portRanges", required=true)
    private Output<List<GetPolicyRulePortRangeArgs>> portRanges;

    /**
     * @return Policy Rule Port Ranges (mutually exclusive with ports)
     * 
     */
    public Output<List<GetPolicyRulePortRangeArgs>> portRanges() {
        return this.portRanges;
    }

    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     * 
     */
    @Import(name="ports", required=true)
    private Output<List<String>> ports;

    /**
     * @return Policy Rule Ports (mutually exclusive with port_ranges)
     * 
     */
    public Output<List<String>> ports() {
        return this.ports;
    }

    /**
     * Policy Rule Protocol (tcp|udp|icmp|all)
     * 
     */
    @Import(name="protocol", required=true)
    private Output<String> protocol;

    /**
     * @return Policy Rule Protocol (tcp|udp|icmp|all)
     * 
     */
    public Output<String> protocol() {
        return this.protocol;
    }

    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     * 
     */
    @Import(name="sourceResource", required=true)
    private Output<GetPolicyRuleSourceResourceArgs> sourceResource;

    /**
     * @return Policy Rule Source Resource (mutually exclusive with sources)
     * 
     */
    public Output<GetPolicyRuleSourceResourceArgs> sourceResource() {
        return this.sourceResource;
    }

    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     * 
     */
    @Import(name="sources", required=true)
    private Output<List<String>> sources;

    /**
     * @return Policy Rule Source Groups (mutually exclusive with source_resource)
     * 
     */
    public Output<List<String>> sources() {
        return this.sources;
    }

    private GetPolicyRuleArgs() {}

    private GetPolicyRuleArgs(GetPolicyRuleArgs $) {
        this.action = $.action;
        this.bidirectional = $.bidirectional;
        this.description = $.description;
        this.destinationResource = $.destinationResource;
        this.destinations = $.destinations;
        this.enabled = $.enabled;
        this.id = $.id;
        this.name = $.name;
        this.portRanges = $.portRanges;
        this.ports = $.ports;
        this.protocol = $.protocol;
        this.sourceResource = $.sourceResource;
        this.sources = $.sources;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPolicyRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPolicyRuleArgs $;

        public Builder() {
            $ = new GetPolicyRuleArgs();
        }

        public Builder(GetPolicyRuleArgs defaults) {
            $ = new GetPolicyRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param action Policy Rule Action (accept|drop)
         * 
         * @return builder
         * 
         */
        public Builder action(Output<String> action) {
            $.action = action;
            return this;
        }

        /**
         * @param action Policy Rule Action (accept|drop)
         * 
         * @return builder
         * 
         */
        public Builder action(String action) {
            return action(Output.of(action));
        }

        /**
         * @param bidirectional Policy Rule Bidirectional
         * 
         * @return builder
         * 
         */
        public Builder bidirectional(Output<Boolean> bidirectional) {
            $.bidirectional = bidirectional;
            return this;
        }

        /**
         * @param bidirectional Policy Rule Bidirectional
         * 
         * @return builder
         * 
         */
        public Builder bidirectional(Boolean bidirectional) {
            return bidirectional(Output.of(bidirectional));
        }

        /**
         * @param description Policy description
         * 
         * @return builder
         * 
         */
        public Builder description(Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Policy description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param destinationResource Policy Rule Destination Resource (mutually exclusive with destinations)
         * 
         * @return builder
         * 
         */
        public Builder destinationResource(Output<GetPolicyRuleDestinationResourceArgs> destinationResource) {
            $.destinationResource = destinationResource;
            return this;
        }

        /**
         * @param destinationResource Policy Rule Destination Resource (mutually exclusive with destinations)
         * 
         * @return builder
         * 
         */
        public Builder destinationResource(GetPolicyRuleDestinationResourceArgs destinationResource) {
            return destinationResource(Output.of(destinationResource));
        }

        /**
         * @param destinations Policy Rule Destination Groups (mutually exclusive with destination_resource)
         * 
         * @return builder
         * 
         */
        public Builder destinations(Output<List<String>> destinations) {
            $.destinations = destinations;
            return this;
        }

        /**
         * @param destinations Policy Rule Destination Groups (mutually exclusive with destination_resource)
         * 
         * @return builder
         * 
         */
        public Builder destinations(List<String> destinations) {
            return destinations(Output.of(destinations));
        }

        /**
         * @param destinations Policy Rule Destination Groups (mutually exclusive with destination_resource)
         * 
         * @return builder
         * 
         */
        public Builder destinations(String... destinations) {
            return destinations(List.of(destinations));
        }

        /**
         * @param enabled Policy Rule Enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Policy Rule Enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param id Policy ID
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Policy ID
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param name Policy Name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Policy Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param portRanges Policy Rule Port Ranges (mutually exclusive with ports)
         * 
         * @return builder
         * 
         */
        public Builder portRanges(Output<List<GetPolicyRulePortRangeArgs>> portRanges) {
            $.portRanges = portRanges;
            return this;
        }

        /**
         * @param portRanges Policy Rule Port Ranges (mutually exclusive with ports)
         * 
         * @return builder
         * 
         */
        public Builder portRanges(List<GetPolicyRulePortRangeArgs> portRanges) {
            return portRanges(Output.of(portRanges));
        }

        /**
         * @param portRanges Policy Rule Port Ranges (mutually exclusive with ports)
         * 
         * @return builder
         * 
         */
        public Builder portRanges(GetPolicyRulePortRangeArgs... portRanges) {
            return portRanges(List.of(portRanges));
        }

        /**
         * @param ports Policy Rule Ports (mutually exclusive with port_ranges)
         * 
         * @return builder
         * 
         */
        public Builder ports(Output<List<String>> ports) {
            $.ports = ports;
            return this;
        }

        /**
         * @param ports Policy Rule Ports (mutually exclusive with port_ranges)
         * 
         * @return builder
         * 
         */
        public Builder ports(List<String> ports) {
            return ports(Output.of(ports));
        }

        /**
         * @param ports Policy Rule Ports (mutually exclusive with port_ranges)
         * 
         * @return builder
         * 
         */
        public Builder ports(String... ports) {
            return ports(List.of(ports));
        }

        /**
         * @param protocol Policy Rule Protocol (tcp|udp|icmp|all)
         * 
         * @return builder
         * 
         */
        public Builder protocol(Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol Policy Rule Protocol (tcp|udp|icmp|all)
         * 
         * @return builder
         * 
         */
        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param sourceResource Policy Rule Source Resource (mutually exclusive with sources)
         * 
         * @return builder
         * 
         */
        public Builder sourceResource(Output<GetPolicyRuleSourceResourceArgs> sourceResource) {
            $.sourceResource = sourceResource;
            return this;
        }

        /**
         * @param sourceResource Policy Rule Source Resource (mutually exclusive with sources)
         * 
         * @return builder
         * 
         */
        public Builder sourceResource(GetPolicyRuleSourceResourceArgs sourceResource) {
            return sourceResource(Output.of(sourceResource));
        }

        /**
         * @param sources Policy Rule Source Groups (mutually exclusive with source_resource)
         * 
         * @return builder
         * 
         */
        public Builder sources(Output<List<String>> sources) {
            $.sources = sources;
            return this;
        }

        /**
         * @param sources Policy Rule Source Groups (mutually exclusive with source_resource)
         * 
         * @return builder
         * 
         */
        public Builder sources(List<String> sources) {
            return sources(Output.of(sources));
        }

        /**
         * @param sources Policy Rule Source Groups (mutually exclusive with source_resource)
         * 
         * @return builder
         * 
         */
        public Builder sources(String... sources) {
            return sources(List.of(sources));
        }

        public GetPolicyRuleArgs build() {
            if ($.action == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "action");
            }
            if ($.bidirectional == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "bidirectional");
            }
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "description");
            }
            if ($.destinationResource == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "destinationResource");
            }
            if ($.destinations == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "destinations");
            }
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "enabled");
            }
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "id");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "name");
            }
            if ($.portRanges == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "portRanges");
            }
            if ($.ports == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "ports");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "protocol");
            }
            if ($.sourceResource == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "sourceResource");
            }
            if ($.sources == null) {
                throw new MissingRequiredPropertyException("GetPolicyRuleArgs", "sources");
            }
            return $;
        }
    }

}
