// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPeerPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPeerPlainArgs Empty = new GetPeerPlainArgs();

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="ip")
    private @Nullable String ip;

    public Optional<String> ip() {
        return Optional.ofNullable(this.ip);
    }

    @Import(name="name")
    private @Nullable String name;

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetPeerPlainArgs() {}

    private GetPeerPlainArgs(GetPeerPlainArgs $) {
        this.id = $.id;
        this.ip = $.ip;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPeerPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPeerPlainArgs $;

        public Builder() {
            $ = new GetPeerPlainArgs();
        }

        public Builder(GetPeerPlainArgs defaults) {
            $ = new GetPeerPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public Builder ip(@Nullable String ip) {
            $.ip = ip;
            return this;
        }

        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetPeerPlainArgs build() {
            return $;
        }
    }

}
