// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPeersArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPeersArgs Empty = new GetPeersArgs();

    @Import(name="approvalRequired")
    private @Nullable Output<Boolean> approvalRequired;

    public Optional<Output<Boolean>> approvalRequired() {
        return Optional.ofNullable(this.approvalRequired);
    }

    @Import(name="cityName")
    private @Nullable Output<String> cityName;

    public Optional<Output<String>> cityName() {
        return Optional.ofNullable(this.cityName);
    }

    @Import(name="connected")
    private @Nullable Output<Boolean> connected;

    public Optional<Output<Boolean>> connected() {
        return Optional.ofNullable(this.connected);
    }

    @Import(name="connectionIp")
    private @Nullable Output<String> connectionIp;

    public Optional<Output<String>> connectionIp() {
        return Optional.ofNullable(this.connectionIp);
    }

    @Import(name="countryCode")
    private @Nullable Output<String> countryCode;

    public Optional<Output<String>> countryCode() {
        return Optional.ofNullable(this.countryCode);
    }

    @Import(name="dnsLabel")
    private @Nullable Output<String> dnsLabel;

    public Optional<Output<String>> dnsLabel() {
        return Optional.ofNullable(this.dnsLabel);
    }

    @Import(name="extraDnsLabels")
    private @Nullable Output<List<String>> extraDnsLabels;

    public Optional<Output<List<String>>> extraDnsLabels() {
        return Optional.ofNullable(this.extraDnsLabels);
    }

    @Import(name="geonameId")
    private @Nullable Output<Integer> geonameId;

    public Optional<Output<Integer>> geonameId() {
        return Optional.ofNullable(this.geonameId);
    }

    @Import(name="groups")
    private @Nullable Output<List<String>> groups;

    public Optional<Output<List<String>>> groups() {
        return Optional.ofNullable(this.groups);
    }

    @Import(name="hostname")
    private @Nullable Output<String> hostname;

    public Optional<Output<String>> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    @Import(name="inactivityExpirationEnabled")
    private @Nullable Output<Boolean> inactivityExpirationEnabled;

    public Optional<Output<Boolean>> inactivityExpirationEnabled() {
        return Optional.ofNullable(this.inactivityExpirationEnabled);
    }

    @Import(name="ip")
    private @Nullable Output<String> ip;

    public Optional<Output<String>> ip() {
        return Optional.ofNullable(this.ip);
    }

    @Import(name="loginExpirationEnabled")
    private @Nullable Output<Boolean> loginExpirationEnabled;

    public Optional<Output<Boolean>> loginExpirationEnabled() {
        return Optional.ofNullable(this.loginExpirationEnabled);
    }

    @Import(name="loginExpired")
    private @Nullable Output<Boolean> loginExpired;

    public Optional<Output<Boolean>> loginExpired() {
        return Optional.ofNullable(this.loginExpired);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="os")
    private @Nullable Output<String> os;

    public Optional<Output<String>> os() {
        return Optional.ofNullable(this.os);
    }

    @Import(name="sshEnabled")
    private @Nullable Output<Boolean> sshEnabled;

    public Optional<Output<Boolean>> sshEnabled() {
        return Optional.ofNullable(this.sshEnabled);
    }

    @Import(name="userId")
    private @Nullable Output<String> userId;

    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    private GetPeersArgs() {}

    private GetPeersArgs(GetPeersArgs $) {
        this.approvalRequired = $.approvalRequired;
        this.cityName = $.cityName;
        this.connected = $.connected;
        this.connectionIp = $.connectionIp;
        this.countryCode = $.countryCode;
        this.dnsLabel = $.dnsLabel;
        this.extraDnsLabels = $.extraDnsLabels;
        this.geonameId = $.geonameId;
        this.groups = $.groups;
        this.hostname = $.hostname;
        this.inactivityExpirationEnabled = $.inactivityExpirationEnabled;
        this.ip = $.ip;
        this.loginExpirationEnabled = $.loginExpirationEnabled;
        this.loginExpired = $.loginExpired;
        this.name = $.name;
        this.os = $.os;
        this.sshEnabled = $.sshEnabled;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPeersArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPeersArgs $;

        public Builder() {
            $ = new GetPeersArgs();
        }

        public Builder(GetPeersArgs defaults) {
            $ = new GetPeersArgs(Objects.requireNonNull(defaults));
        }

        public Builder approvalRequired(@Nullable Output<Boolean> approvalRequired) {
            $.approvalRequired = approvalRequired;
            return this;
        }

        public Builder approvalRequired(Boolean approvalRequired) {
            return approvalRequired(Output.of(approvalRequired));
        }

        public Builder cityName(@Nullable Output<String> cityName) {
            $.cityName = cityName;
            return this;
        }

        public Builder cityName(String cityName) {
            return cityName(Output.of(cityName));
        }

        public Builder connected(@Nullable Output<Boolean> connected) {
            $.connected = connected;
            return this;
        }

        public Builder connected(Boolean connected) {
            return connected(Output.of(connected));
        }

        public Builder connectionIp(@Nullable Output<String> connectionIp) {
            $.connectionIp = connectionIp;
            return this;
        }

        public Builder connectionIp(String connectionIp) {
            return connectionIp(Output.of(connectionIp));
        }

        public Builder countryCode(@Nullable Output<String> countryCode) {
            $.countryCode = countryCode;
            return this;
        }

        public Builder countryCode(String countryCode) {
            return countryCode(Output.of(countryCode));
        }

        public Builder dnsLabel(@Nullable Output<String> dnsLabel) {
            $.dnsLabel = dnsLabel;
            return this;
        }

        public Builder dnsLabel(String dnsLabel) {
            return dnsLabel(Output.of(dnsLabel));
        }

        public Builder extraDnsLabels(@Nullable Output<List<String>> extraDnsLabels) {
            $.extraDnsLabels = extraDnsLabels;
            return this;
        }

        public Builder extraDnsLabels(List<String> extraDnsLabels) {
            return extraDnsLabels(Output.of(extraDnsLabels));
        }

        public Builder extraDnsLabels(String... extraDnsLabels) {
            return extraDnsLabels(List.of(extraDnsLabels));
        }

        public Builder geonameId(@Nullable Output<Integer> geonameId) {
            $.geonameId = geonameId;
            return this;
        }

        public Builder geonameId(Integer geonameId) {
            return geonameId(Output.of(geonameId));
        }

        public Builder groups(@Nullable Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        public Builder hostname(@Nullable Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        public Builder inactivityExpirationEnabled(@Nullable Output<Boolean> inactivityExpirationEnabled) {
            $.inactivityExpirationEnabled = inactivityExpirationEnabled;
            return this;
        }

        public Builder inactivityExpirationEnabled(Boolean inactivityExpirationEnabled) {
            return inactivityExpirationEnabled(Output.of(inactivityExpirationEnabled));
        }

        public Builder ip(@Nullable Output<String> ip) {
            $.ip = ip;
            return this;
        }

        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        public Builder loginExpirationEnabled(@Nullable Output<Boolean> loginExpirationEnabled) {
            $.loginExpirationEnabled = loginExpirationEnabled;
            return this;
        }

        public Builder loginExpirationEnabled(Boolean loginExpirationEnabled) {
            return loginExpirationEnabled(Output.of(loginExpirationEnabled));
        }

        public Builder loginExpired(@Nullable Output<Boolean> loginExpired) {
            $.loginExpired = loginExpired;
            return this;
        }

        public Builder loginExpired(Boolean loginExpired) {
            return loginExpired(Output.of(loginExpired));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder os(@Nullable Output<String> os) {
            $.os = os;
            return this;
        }

        public Builder os(String os) {
            return os(Output.of(os));
        }

        public Builder sshEnabled(@Nullable Output<Boolean> sshEnabled) {
            $.sshEnabled = sshEnabled;
            return this;
        }

        public Builder sshEnabled(Boolean sshEnabled) {
            return sshEnabled(Output.of(sshEnabled));
        }

        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public GetPeersArgs build() {
            return $;
        }
    }

}
