// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NameserverGroupNameserverArgs extends com.pulumi.resources.ResourceArgs {

    public static final NameserverGroupNameserverArgs Empty = new NameserverGroupNameserverArgs();

    /**
     * Nameserver IP
     * 
     */
    @Import(name="ip", required=true)
    private Output<String> ip;

    /**
     * @return Nameserver IP
     * 
     */
    public Output<String> ip() {
        return this.ip;
    }

    /**
     * Nameserver Type
     * 
     */
    @Import(name="nsType")
    private @Nullable Output<String> nsType;

    /**
     * @return Nameserver Type
     * 
     */
    public Optional<Output<String>> nsType() {
        return Optional.ofNullable(this.nsType);
    }

    /**
     * Nameserver Port
     * 
     */
    @Import(name="port")
    private @Nullable Output<Integer> port;

    /**
     * @return Nameserver Port
     * 
     */
    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    private NameserverGroupNameserverArgs() {}

    private NameserverGroupNameserverArgs(NameserverGroupNameserverArgs $) {
        this.ip = $.ip;
        this.nsType = $.nsType;
        this.port = $.port;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NameserverGroupNameserverArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NameserverGroupNameserverArgs $;

        public Builder() {
            $ = new NameserverGroupNameserverArgs();
        }

        public Builder(NameserverGroupNameserverArgs defaults) {
            $ = new NameserverGroupNameserverArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ip Nameserver IP
         * 
         * @return builder
         * 
         */
        public Builder ip(Output<String> ip) {
            $.ip = ip;
            return this;
        }

        /**
         * @param ip Nameserver IP
         * 
         * @return builder
         * 
         */
        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        /**
         * @param nsType Nameserver Type
         * 
         * @return builder
         * 
         */
        public Builder nsType(@Nullable Output<String> nsType) {
            $.nsType = nsType;
            return this;
        }

        /**
         * @param nsType Nameserver Type
         * 
         * @return builder
         * 
         */
        public Builder nsType(String nsType) {
            return nsType(Output.of(nsType));
        }

        /**
         * @param port Nameserver Port
         * 
         * @return builder
         * 
         */
        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port Nameserver Port
         * 
         * @return builder
         * 
         */
        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public NameserverGroupNameserverArgs build() {
            if ($.ip == null) {
                throw new MissingRequiredPropertyException("NameserverGroupNameserverArgs", "ip");
            }
            return $;
        }
    }

}
