// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.netbird.netbird.inputs.NameserverGroupNameserverArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NameserverGroupState extends com.pulumi.resources.ResourceArgs {

    public static final NameserverGroupState Empty = new NameserverGroupState();

    /**
     * Description of the nameserver group
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description of the nameserver group
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Match domain list. It should be empty only if primary is true.
     * 
     */
    @Import(name="domains")
    private @Nullable Output<List<String>> domains;

    /**
     * @return Match domain list. It should be empty only if primary is true.
     * 
     */
    public Optional<Output<List<String>>> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * Nameserver group status
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Nameserver group status
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Distribution group IDs that defines group of peers that will use this nameserver group
     * 
     */
    @Import(name="groups")
    private @Nullable Output<List<String>> groups;

    /**
     * @return Distribution group IDs that defines group of peers that will use this nameserver group
     * 
     */
    public Optional<Output<List<String>>> groups() {
        return Optional.ofNullable(this.groups);
    }

    /**
     * Name of nameserver group
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of nameserver group
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Nameserver list
     * 
     */
    @Import(name="nameservers")
    private @Nullable Output<List<NameserverGroupNameserverArgs>> nameservers;

    /**
     * @return Nameserver list
     * 
     */
    public Optional<Output<List<NameserverGroupNameserverArgs>>> nameservers() {
        return Optional.ofNullable(this.nameservers);
    }

    /**
     * Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
     * 
     */
    @Import(name="primary")
    private @Nullable Output<Boolean> primary;

    /**
     * @return Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
     * 
     */
    public Optional<Output<Boolean>> primary() {
        return Optional.ofNullable(this.primary);
    }

    /**
     * Search domain status for match domains. It should be true only if domains list is not empty.
     * 
     */
    @Import(name="searchDomainsEnabled")
    private @Nullable Output<Boolean> searchDomainsEnabled;

    /**
     * @return Search domain status for match domains. It should be true only if domains list is not empty.
     * 
     */
    public Optional<Output<Boolean>> searchDomainsEnabled() {
        return Optional.ofNullable(this.searchDomainsEnabled);
    }

    private NameserverGroupState() {}

    private NameserverGroupState(NameserverGroupState $) {
        this.description = $.description;
        this.domains = $.domains;
        this.enabled = $.enabled;
        this.groups = $.groups;
        this.name = $.name;
        this.nameservers = $.nameservers;
        this.primary = $.primary;
        this.searchDomainsEnabled = $.searchDomainsEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NameserverGroupState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NameserverGroupState $;

        public Builder() {
            $ = new NameserverGroupState();
        }

        public Builder(NameserverGroupState defaults) {
            $ = new NameserverGroupState(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Description of the nameserver group
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description of the nameserver group
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param domains Match domain list. It should be empty only if primary is true.
         * 
         * @return builder
         * 
         */
        public Builder domains(@Nullable Output<List<String>> domains) {
            $.domains = domains;
            return this;
        }

        /**
         * @param domains Match domain list. It should be empty only if primary is true.
         * 
         * @return builder
         * 
         */
        public Builder domains(List<String> domains) {
            return domains(Output.of(domains));
        }

        /**
         * @param domains Match domain list. It should be empty only if primary is true.
         * 
         * @return builder
         * 
         */
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }

        /**
         * @param enabled Nameserver group status
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Nameserver group status
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param groups Distribution group IDs that defines group of peers that will use this nameserver group
         * 
         * @return builder
         * 
         */
        public Builder groups(@Nullable Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        /**
         * @param groups Distribution group IDs that defines group of peers that will use this nameserver group
         * 
         * @return builder
         * 
         */
        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        /**
         * @param groups Distribution group IDs that defines group of peers that will use this nameserver group
         * 
         * @return builder
         * 
         */
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        /**
         * @param name Name of nameserver group
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of nameserver group
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nameservers Nameserver list
         * 
         * @return builder
         * 
         */
        public Builder nameservers(@Nullable Output<List<NameserverGroupNameserverArgs>> nameservers) {
            $.nameservers = nameservers;
            return this;
        }

        /**
         * @param nameservers Nameserver list
         * 
         * @return builder
         * 
         */
        public Builder nameservers(List<NameserverGroupNameserverArgs> nameservers) {
            return nameservers(Output.of(nameservers));
        }

        /**
         * @param nameservers Nameserver list
         * 
         * @return builder
         * 
         */
        public Builder nameservers(NameserverGroupNameserverArgs... nameservers) {
            return nameservers(List.of(nameservers));
        }

        /**
         * @param primary Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
         * 
         * @return builder
         * 
         */
        public Builder primary(@Nullable Output<Boolean> primary) {
            $.primary = primary;
            return this;
        }

        /**
         * @param primary Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
         * 
         * @return builder
         * 
         */
        public Builder primary(Boolean primary) {
            return primary(Output.of(primary));
        }

        /**
         * @param searchDomainsEnabled Search domain status for match domains. It should be true only if domains list is not empty.
         * 
         * @return builder
         * 
         */
        public Builder searchDomainsEnabled(@Nullable Output<Boolean> searchDomainsEnabled) {
            $.searchDomainsEnabled = searchDomainsEnabled;
            return this;
        }

        /**
         * @param searchDomainsEnabled Search domain status for match domains. It should be true only if domains list is not empty.
         * 
         * @return builder
         * 
         */
        public Builder searchDomainsEnabled(Boolean searchDomainsEnabled) {
            return searchDomainsEnabled(Output.of(searchDomainsEnabled));
        }

        public NameserverGroupState build() {
            return $;
        }
    }

}
