// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetReverseProxyService
    {
        public static Task<GetReverseProxyServiceResult> InvokeAsync(GetReverseProxyServiceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetReverseProxyServiceResult>("netbird:index/getReverseProxyService:getReverseProxyService", args ?? new GetReverseProxyServiceArgs(), options.WithDefaults());

        public static Output<GetReverseProxyServiceResult> Invoke(GetReverseProxyServiceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetReverseProxyServiceResult>("netbird:index/getReverseProxyService:getReverseProxyService", args ?? new GetReverseProxyServiceInvokeArgs(), options.WithDefaults());

        public static Output<GetReverseProxyServiceResult> Invoke(GetReverseProxyServiceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetReverseProxyServiceResult>("netbird:index/getReverseProxyService:getReverseProxyService", args ?? new GetReverseProxyServiceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetReverseProxyServiceArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain")]
        public string? Domain { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetReverseProxyServiceArgs()
        {
        }
        public static new GetReverseProxyServiceArgs Empty => new GetReverseProxyServiceArgs();
    }

    public sealed class GetReverseProxyServiceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetReverseProxyServiceInvokeArgs()
        {
        }
        public static new GetReverseProxyServiceInvokeArgs Empty => new GetReverseProxyServiceInvokeArgs();
    }


    [OutputType]
    public sealed class GetReverseProxyServiceResult
    {
        public readonly Outputs.GetReverseProxyServiceAuthResult Auth;
        public readonly string Domain;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string Name;
        public readonly bool PassHostHeader;
        public readonly string ProxyCluster;
        public readonly bool RewriteRedirects;
        public readonly ImmutableArray<Outputs.GetReverseProxyServiceTargetResult> Targets;

        [OutputConstructor]
        private GetReverseProxyServiceResult(
            Outputs.GetReverseProxyServiceAuthResult auth,

            string domain,

            bool enabled,

            string id,

            string name,

            bool passHostHeader,

            string proxyCluster,

            bool rewriteRedirects,

            ImmutableArray<Outputs.GetReverseProxyServiceTargetResult> targets)
        {
            Auth = auth;
            Domain = domain;
            Enabled = enabled;
            Id = id;
            Name = name;
            PassHostHeader = passHostHeader;
            ProxyCluster = proxyCluster;
            RewriteRedirects = rewriteRedirects;
            Targets = targets;
        }
    }
}
