// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class ReverseProxyServiceAuthArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Bearer token authentication
        /// </summary>
        [Input("bearerAuth")]
        public Input<Inputs.ReverseProxyServiceAuthBearerAuthArgs>? BearerAuth { get; set; }

        /// <summary>
        /// Link authentication
        /// </summary>
        [Input("linkAuth")]
        public Input<Inputs.ReverseProxyServiceAuthLinkAuthArgs>? LinkAuth { get; set; }

        /// <summary>
        /// Password authentication
        /// </summary>
        [Input("passwordAuth")]
        public Input<Inputs.ReverseProxyServiceAuthPasswordAuthArgs>? PasswordAuth { get; set; }

        /// <summary>
        /// PIN authentication
        /// </summary>
        [Input("pinAuth")]
        public Input<Inputs.ReverseProxyServiceAuthPinAuthArgs>? PinAuth { get; set; }

        public ReverseProxyServiceAuthArgs()
        {
        }
        public static new ReverseProxyServiceAuthArgs Empty => new ReverseProxyServiceAuthArgs();
    }
}
