// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class ReverseProxyServiceTargetGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether this target is enabled
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// URL path prefix for this target. Defaults to "/" if omitted.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Backend port for this target (0 for scheme default)
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        /// <summary>
        /// Protocol to use when connecting to the backend (http, https)
        /// </summary>
        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        /// <summary>
        /// Target ID (resource or peer ID)
        /// </summary>
        [Input("targetId", required: true)]
        public Input<string> TargetId { get; set; } = null!;

        /// <summary>
        /// Target type (peer, host, domain, subnet)
        /// </summary>
        [Input("targetType", required: true)]
        public Input<string> TargetType { get; set; } = null!;

        public ReverseProxyServiceTargetGetArgs()
        {
        }
        public static new ReverseProxyServiceTargetGetArgs Empty => new ReverseProxyServiceTargetGetArgs();
    }
}
