// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetPolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: string;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in `sources`. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: {[key: string]: string[]};
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: boolean;
    /**
     * Policy description
     */
    description?: string;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: inputs.GetPolicyRuleDestinationResource;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: string[];
    /**
     * Policy Rule Enabled
     */
    enabled?: boolean;
    /**
     * Policy ID
     */
    id?: string;
    /**
     * Policy Name
     */
    name?: string;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: inputs.GetPolicyRulePortRange[];
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: string[];
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: string;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: inputs.GetPolicyRuleSourceResource;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: string[];
}

export interface GetPolicyRuleArgs {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: pulumi.Input<string>;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in `sources`. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: pulumi.Input<boolean>;
    /**
     * Policy description
     */
    description?: pulumi.Input<string>;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: pulumi.Input<inputs.GetPolicyRuleDestinationResourceArgs>;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Policy Rule Enabled
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Policy ID
     */
    id?: pulumi.Input<string>;
    /**
     * Policy Name
     */
    name?: pulumi.Input<string>;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: pulumi.Input<pulumi.Input<inputs.GetPolicyRulePortRangeArgs>[]>;
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: pulumi.Input<string>;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: pulumi.Input<inputs.GetPolicyRuleSourceResourceArgs>;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface GetPolicyRuleDestinationResource {
    id: string;
    type: string;
}

export interface GetPolicyRuleDestinationResourceArgs {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface GetPolicyRulePortRange {
    end?: number;
    start?: number;
}

export interface GetPolicyRulePortRangeArgs {
    end?: pulumi.Input<number>;
    start?: pulumi.Input<number>;
}

export interface GetPolicyRuleSourceResource {
    id: string;
    type: string;
}

export interface GetPolicyRuleSourceResourceArgs {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface NameserverGroupNameserver {
    /**
     * Nameserver IP
     */
    ip: pulumi.Input<string>;
    /**
     * Nameserver Type
     */
    nsType?: pulumi.Input<string>;
    /**
     * Nameserver Port
     */
    port?: pulumi.Input<number>;
}

export interface PolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: pulumi.Input<string>;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in `sources`. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: pulumi.Input<boolean>;
    /**
     * Policy description
     */
    description?: pulumi.Input<string>;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: pulumi.Input<inputs.PolicyRuleDestinationResource>;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Policy Rule Enabled
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Policy ID
     */
    id?: pulumi.Input<string>;
    /**
     * Policy Name
     */
    name: pulumi.Input<string>;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: pulumi.Input<pulumi.Input<inputs.PolicyRulePortRange>[]>;
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: pulumi.Input<string>;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: pulumi.Input<inputs.PolicyRuleSourceResource>;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface PolicyRuleDestinationResource {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface PolicyRulePortRange {
    end: pulumi.Input<number>;
    start: pulumi.Input<number>;
}

export interface PolicyRuleSourceResource {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface PostureCheckGeoLocationCheck {
    action?: pulumi.Input<string>;
    locations?: pulumi.Input<pulumi.Input<inputs.PostureCheckGeoLocationCheckLocation>[]>;
}

export interface PostureCheckGeoLocationCheckLocation {
    cityName?: pulumi.Input<string>;
    countryCode: pulumi.Input<string>;
}

export interface PostureCheckNetbirdVersionCheck {
    minVersion?: pulumi.Input<string>;
}

export interface PostureCheckOsVersionCheck {
    androidMinVersion?: pulumi.Input<string>;
    darwinMinVersion?: pulumi.Input<string>;
    iosMinVersion?: pulumi.Input<string>;
    linuxMinKernelVersion?: pulumi.Input<string>;
    windowsMinKernelVersion?: pulumi.Input<string>;
}

export interface PostureCheckPeerNetworkRangeCheck {
    action?: pulumi.Input<string>;
    ranges?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface PostureCheckProcessCheck {
    linuxPath?: pulumi.Input<string>;
    macPath?: pulumi.Input<string>;
    windowsPath?: pulumi.Input<string>;
}

export interface ReverseProxyServiceAuth {
    /**
     * Bearer token authentication
     */
    bearerAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthBearerAuth>;
    /**
     * Link authentication
     */
    linkAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthLinkAuth>;
    /**
     * Password authentication
     */
    passwordAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthPasswordAuth>;
    /**
     * PIN authentication
     */
    pinAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthPinAuth>;
}

export interface ReverseProxyServiceAuthBearerAuth {
    /**
     * List of group IDs that can use bearer auth
     */
    distributionGroups?: pulumi.Input<pulumi.Input<string>[]>;
    enabled: pulumi.Input<boolean>;
}

export interface ReverseProxyServiceAuthLinkAuth {
    enabled: pulumi.Input<boolean>;
}

export interface ReverseProxyServiceAuthPasswordAuth {
    enabled: pulumi.Input<boolean>;
    password?: pulumi.Input<string>;
}

export interface ReverseProxyServiceAuthPinAuth {
    enabled: pulumi.Input<boolean>;
    pin?: pulumi.Input<string>;
}

export interface ReverseProxyServiceTarget {
    /**
     * Whether this target is enabled
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
     */
    host?: pulumi.Input<string>;
    /**
     * URL path prefix for this target. Defaults to "/" if omitted.
     */
    path?: pulumi.Input<string>;
    /**
     * Backend port for this target (0 for scheme default)
     */
    port: pulumi.Input<number>;
    /**
     * Protocol to use when connecting to the backend (http, https)
     */
    protocol: pulumi.Input<string>;
    /**
     * Target ID (resource or peer ID)
     */
    targetId: pulumi.Input<string>;
    /**
     * Target type (peer, host, domain, subnet)
     */
    targetType: pulumi.Input<string>;
}
