// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbird.Inputs
{

    public sealed class GetPolicyRulePortRangeArgs : global::Pulumi.InvokeArgs
    {
        [Input("end", required: true)]
        public int End { get; set; }

        [Input("start", required: true)]
        public int Start { get; set; }

        public GetPolicyRulePortRangeArgs()
        {
        }
        public static new GetPolicyRulePortRangeArgs Empty => new GetPolicyRulePortRangeArgs();
    }
}
