// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NetworkResource extends pulumi.CustomResource {
    /**
     * Get an existing NetworkResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkResourceState, opts?: pulumi.CustomResourceOptions): NetworkResource {
        return new NetworkResource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/networkResource:NetworkResource';

    /**
     * Returns true if the given object is an instance of NetworkResource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkResource.__pulumiType;
    }

    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains
     * like example.com and *.example.com)
     */
    public readonly address!: pulumi.Output<string>;
    /**
     * NetworkResource Description
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * NetworkResource status
     */
    public readonly enabled!: pulumi.Output<boolean>;
    /**
     * Group IDs containing the resource
     */
    public readonly groups!: pulumi.Output<string[]>;
    /**
     * NetworkResource Name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The unique identifier of a network
     */
    public readonly networkId!: pulumi.Output<string>;

    /**
     * Create a NetworkResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkResourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkResourceArgs | NetworkResourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkResourceState | undefined;
            resourceInputs["address"] = state ? state.address : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["groups"] = state ? state.groups : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
        } else {
            const args = argsOrState as NetworkResourceArgs | undefined;
            if ((!args || args.address === undefined) && !opts.urn) {
                throw new Error("Missing required property 'address'");
            }
            if ((!args || args.groups === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groups'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.networkId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["address"] = args ? args.address : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["groups"] = args ? args.groups : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkId"] = args ? args.networkId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkResource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NetworkResource resources.
 */
export interface NetworkResourceState {
    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains
     * like example.com and *.example.com)
     */
    address?: pulumi.Input<string>;
    /**
     * NetworkResource Description
     */
    description?: pulumi.Input<string>;
    /**
     * NetworkResource status
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Group IDs containing the resource
     */
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * NetworkResource Name
     */
    name?: pulumi.Input<string>;
    /**
     * The unique identifier of a network
     */
    networkId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NetworkResource resource.
 */
export interface NetworkResourceArgs {
    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains
     * like example.com and *.example.com)
     */
    address: pulumi.Input<string>;
    /**
     * NetworkResource Description
     */
    description?: pulumi.Input<string>;
    /**
     * NetworkResource status
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Group IDs containing the resource
     */
    groups: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * NetworkResource Name
     */
    name: pulumi.Input<string>;
    /**
     * The unique identifier of a network
     */
    networkId: pulumi.Input<string>;
}
